import Foundation

/// Tabela canônica de traduções para Inglês US (regionalização integral).
/// Garante que todos os textos regionalizados resolvam com latência zero e 100% de confiabilidade.
public enum TabelaDeStrings: Sendable {
    public static let en: [String: String] = [
        "%@ cópia": "%@ copy",
        "%@ de %@": "%@ of %@",
        "%@ já está com transcrição e resumo prontos.": "%@ transcription and summary are ready.",
        "%@ não teve fala reconhecida.": "%@ had no recognized speech.",
        "%@ vence %@ e foi marcada como prioridade alta.": "%@ is due %@ and was marked as high priority.",
        "%@. %@": "%@. %@",
        "%d alteração(ões) aguardando nova tentativa no iCloud%@": "iCloud changes awaiting retry: %d%@",
        "%d alteração(ões) continuam na fila do iCloud.": "Pending iCloud operations: %d",
        "%d arquivos": "%d files",
        "%d conversa(s) têm uma edição local pendente; a cópia local foi preservada até o próximo envio.": "Conversations with pending local edits: %d. Local copies are preserved until the next sync.",
        "%d conversas": "%d conversations",
        "%d conversas selecionadas": "%d conversations selected",
        "%d de %d": "%d of %d",
        "%d de %d membros": "%d of %d members",
        "%d membros": "%d members",
        "%d ocorrências": "%d occurrences",
        "%d participantes": "%d participants",
        "%d reunião(ões) com participantes — sincronizadas automaticamente na aba Calendário da biblioteca.": "Meetings with attendees: %d — automatically synced in the Library Calendar tab.",
        "%d reuniões": "%d meetings",
        "%d segundos": "%d seconds",
        ".": ".",
        "1 arquivo": "1 file",
        "1 conversa": "1 conversation",
        "1 membro": "1 member",
        "1 nota": "1 note",
        "1 ocorrência": "1 occurrence",
        "1 participante": "1 participant",
        "1 reunião": "1 meeting",
        "1 segundo": "1 second",
        "42 min": "42 min",
        "A transcrição aparecerá aqui conforme o áudio for processado.": "Transcription will appear here as audio is processed.",
        "A transcrição falhou": "Transcription failed",
        "AO VIVO": "LIVE",
        "Abrir": "Open",
        "Abrir a pasta %@": "Open %@ folder",
        "Abrir no app": "Open in app",
        "Abrir pasta": "Open folder",
        "Aceitar e mandar para o quadro": "Accept and send to board",
        "Acesso": "Access",
        "Acesso e exclusão": "Access & Deletion",
        "Acompanha o ajuste de aparência do seu Mac.": "Matches your Mac's appearance setting.",
        "Adiciona esta conversa à fila. O resumo será feito após a transcrição.": "Adds this conversation to queue. Summary will be generated after transcription.",
        "Adicionar": "Add",
        "Adicionar mídia": "Add media",
        "Adicionar nova equipe": "Add new team",
        "Adicionar participante": "Add participant",
        "Adicionar pasta": "Add folder",
        "Adicionar pessoa": "Add person",
        "Adicionar tarefa": "Add task",
        "Adicionar uma pasta": "Add a folder",
        "Adicione uma descrição": "Add a description",
        "Administrador": "Administrator",
        "Aguardando": "Waiting",
        "Aguardando download": "Waiting for download",
        "Aguardando modelos": "Waiting for models",
        "Aguardando transcrição": "Waiting for transcription",
        "Ajustar": "Fit",
        "Ajustar capa": "Adjust cover",
        "Ajustes": "Settings",
        "Alinhamento dos Falantes": "Speaker Alignment",
        "Alta": "High",
        "Alternar": "Toggle",
        "Amanhã": "Tomorrow",
        "Anexo": "Attachment",
        "Anexos": "Attachments",
        "Anexos de Mídia": "Media Attachments",
        "Ao finalizar, a conversa será salva na biblioteca.": "When finished, conversation will be saved to library.",
        "Apagar": "Delete",
        "Apagar anexo": "Delete attachment",
        "Apagar anexo definitivamente?": "Delete attachment permanently?",
        "Apagar definitivamente": "Delete permanently",
        "Apagar definitivamente?": "Delete permanently?",
        "Apagar nota": "Delete note",
        "Apagar pasta": "Delete folder",
        "Apagar perfil": "Delete profile",
        "Aparência": "Appearance",
        "Aparência dos Cards": "Card Appearance",
        "Apenas no Mac": "On Mac only",
        "Arquivo": "File",
        "Arquivo importado": "Imported file",
        "Arquivos": "Files",
        "Arraste tarefas para cá": "Drag tasks here",
        "Arraste uma tarefa para cá": "Drag a task here",
        "Atalhos": "Shortcuts",
        "Atalhos de teclado": "Keyboard shortcuts",
        "Atividade": "Activity",
        "Atrasada": "Overdue",
        "Atrasadas": "Overdue",
        "Atualizando": "Updating",
        "Atualizando arquivo na lixeira": "Updating file in trash",
        "Atualizar": "Update",
        "Atualize os dados que aparecem no card e no cabeçalho.": "Update the information shown on the card and header.",
        "Autorize no navegador e volte ao Ōmu…": "Authorize in browser and return to Ōmu…",
        "Autorize o microfone em Ajustes do Sistema › Privacidade › Microfone.": "Allow microphone access in System Settings › Privacy › Microphone.",
        "Autorize o reconhecimento de fala em Ajustes do Sistema › Privacidade.": "Allow speech recognition in System Settings › Privacy.",
        "Avançar 10 segundos": "Forward 10 seconds",
        "Ações": "Actions",
        "Ações da pasta": "Folder actions",
        "Ações da tarefa": "Task actions",
        "Ações do card": "Card actions",
        "Baixa": "Low",
        "Baixando": "Downloading",
        "Baixando modelos…": "Downloading models…",
        "Biblioteca": "Library",
        "Biblioteca de conversas": "Conversation library",
        "Buscar": "Search",
        "Buscar conversas…": "Search conversations…",
        "Buscar mídias…": "Search media…",
        "Buscar na lixeira…": "Search trash…",
        "Buscar tarefas…": "Search tasks…",
        "Cabeçalho": "Header",
        "Calendário": "Calendar",
        "Campo obrigatório": "Required field",
        "Cancelar": "Cancel",
        "Cancelar a gravação?": "Cancel recording?",
        "Cancelar gravação": "Cancel recording",
        "Capa": "Cover",
        "Card": "Card",
        "Carregando…": "Loading…",
        "Claro": "Light",
        "Coluna recolhida — pode soltar aqui.": "Column collapsed — drop here.",
        "Compartilhado": "Shared",
        "Compartilhamento": "Sharing",
        "Compartilhar": "Share",
        "Concluir": "Complete",
        "Concluir edição": "Finish editing",
        "Concluir gravação": "Finish recording",
        "Concluída": "Completed",
        "Concluídas": "Completed",
        "Concluído": "Completed",
        "Conectado": "Connected",
        "Conectar conta Google…": "Connect Google account…",
        "Conectar conta Granola…": "Connect Granola account…",
        "Configurações": "Settings",
        "Configurações da equipe": "Team settings",
        "Configure os detalhes da sua nova sessão": "Configure your new session details",
        "Conflito de sincronização": "Sync conflict",
        "Conta ativa": "Active account",
        "Conta ativa: %@": "Active account: %@",
        "Conta pessoal": "Personal account",
        "Continuar": "Resume",
        "Continuar gravando": "Keep recording",
        "Continuar gravação": "Resume recording",
        "Conversa": "Conversation",
        "Conversa %@. %@": "Conversation %@. %@",
        "Conversas": "Conversations",
        "Cor": "Color",
        "Cor de destaque": "Accent color",
        "Corrija a nota…": "Edit note…",
        "Criar": "Create",
        "Criar equipe": "Create team",
        "Criar nova pasta": "Create new folder",
        "Criar pasta": "Create folder",
        "Criar tarefa": "Create task",
        "Código": "Code",
        "Código da equipe": "Team code",
        "Código de convite": "Invite code",
        "Dados locais": "Local data",
        "Data": "Date",
        "Data da entrevista": "Interview date",
        "Data de entrega": "Due date",
        "Data e hora": "Date & Time",
        "Data limite": "Due date",
        "Data não reconhecida. Use dd/mm/aaaa.": "Unrecognized date. Use mm/dd/yyyy.",
        "Deletar": "Delete",
        "Descartar": "Discard",
        "Descartar sugestão": "Discard suggestion",
        "Descrição": "Description",
        "Descrição da tarefa": "Task description",
        "Desmarcar %@": "Deselect %@",
        "Destino": "Destination",
        "Detalhes": "Details",
        "Detalhes da conversa": "Conversation details",
        "Detalhes, contexto ou o que precisa ser feito": "Details, context, or what needs to be done",
        "Diarização": "Diarization",
        "Digite a data": "Enter date",
        "Digite o nome da pasta": "Enter folder name",
        "Dispensar": "Dismiss",
        "Dispensar mensagem de erro": "Dismiss error message",
        "Disponível depois que o resumo estiver pronto": "Available once summary is ready",
        "Distinguir falantes": "Distinguish speakers",
        "Ditar nota": "Dictate note",
        "Dono": "Owner",
        "Duplicar": "Duplicate",
        "Duração": "Duration",
        "E-mail": "Email",
        "Editar": "Edit",
        "Editar antes de aceitar": "Edit before accepting",
        "Editar informações": "Edit details",
        "Editar nota": "Edit note",
        "Editar pasta": "Edit folder",
        "Editar tarefa": "Edit task",
        "Elementos": "Elements",
        "Em andamento": "In Progress",
        "Enter salva · Enter vazio marca o instante": "Enter saves · Empty Enter bookmarks timestamp",
        "Entrar com Apple": "Sign in with Apple",
        "Entrevista": "Interview",
        "Entrevistado": "Interviewee",
        "Entrevistadores": "Interviewers",
        "Equipe": "Team",
        "Equipes": "Teams",
        "Erro": "Error",
        "Erro ao carregar": "Error loading",
        "Erro ao salvar": "Error saving",
        "Escolha uma foto para %@": "Choose a photo for %@",
        "Escolher…": "Choose…",
        "Escreva e pressione Enter…": "Write and press Enter…",
        "Escreva o nome primeiro": "Enter a name first",
        "Escreva uma nota e pressione Enter…": "Write a note and press Enter…",
        "Escuro": "Dark",
        "Esvaziar Lixeira": "Empty Trash",
        "Esvaziar lixeira": "Empty trash",
        "Eu": "Me",
        "Eu · microfone": "Me · microphone",
        "Ex.: Ana Silva": "e.g., Ana Silva",
        "Ex.: Entrevista com Stakeholders - UX Research": "e.g., Stakeholder Interview - UX Research",
        "Ex.: João Santos": "e.g., João Santos",
        "Excluir": "Delete",
        "Excluir esta tarefa?": "Delete this task?",
        "Excluir perfil": "Delete profile",
        "Exportar": "Export",
        "Exportar Markdown": "Export Markdown",
        "Exportar com áudio": "Export with audio",
        "Exportar áudio": "Export audio",
        "Externos": "External",
        "Falante": "Speaker",
        "Falante %d": "Speaker %d",
        "Falantes": "Speakers",
        "Favoritos": "Favorites",
        "Fechar": "Close",
        "Fechar sem salvar": "Close without saving",
        "Ficha da conversa": "Conversation sheet",
        "Fila de processamento": "Processing queue",
        "Filtro": "Filter",
        "Filtros": "Filters",
        "Finalizar": "Finish",
        "Finalizar gravação": "End recording",
        "Formato": "Format",
        "Foto": "Photo",
        "Foto de %@": "Photo of %@",
        "Geral": "General",
        "Gerenciar": "Manage",
        "Gerenciar equipe": "Manage team",
        "Gerenciar perfil": "Manage profile",
        "Google Calendar": "Google Calendar",
        "Grade": "Grid",
        "Granola": "Granola",
        "Gravado": "Recorded",
        "Gravando": "Recording",
        "Gravando agora": "Recording now",
        "Gravar": "Record",
        "Gravação": "Recording",
        "Gravação ativa": "Active recording",
        "Gravação pausada": "Recording paused",
        "Histórico": "History",
        "Hoje": "Today",
        "Hora": "Time",
        "Idioma": "Language",
        "Importado para o app em %@": "Imported into the app on %@",
        "Importar": "Import",
        "Importar áudio": "Import audio",
        "Informações": "Information",
        "Informações da reunião": "Meeting details",
        "Iniciar gravação": "Start recording",
        "Janela": "Window",
        "Layout": "Layout",
        "Legenda": "Caption",
        "Limpar": "Clear",
        "Limpar busca": "Clear search",
        "Limpar seleção": "Clear selection",
        "Linha do tempo": "Timeline",
        "Lista": "List",
        "Lixeira": "Trash",
        "Mais ações": "More actions",
        "Marcar %@": "Select %@",
        "Marcar como em andamento": "Mark as in progress",
        "Membro": "Member",
        "Membros": "Members",
        "Menu": "Menu",
        "Microfone": "Microphone",
        "Minimizar": "Minimize",
        "Modelos": "Models",
        "Modo": "Mode",
        "Mostrar": "Show",
        "Mostrar as tarefas ocultas": "Show hidden tasks",
        "Mostrar coluna %@": "Show %@ column",
        "Mostrar seção %@": "Show %@ section",
        "Mostrar tarefa": "Show task",
        "Mover": "Move",
        "Mover para a lixeira": "Move to trash",
        "Mover para pasta": "Move to folder",
        "Média": "Medium",
        "Mídia": "Media",
        "Mídias": "Media",
        "Nenhum arquivo": "No files",
        "Nenhum aviso ainda.": "No notifications yet.",
        "Nenhum informado": "None specified",
        "Nenhuma conversa": "No conversations",
        "Nenhuma conversa encontrada": "No conversations found",
        "Nenhuma equipe ainda": "No teams yet",
        "Nenhuma nota": "No notes",
        "Nenhuma pasta": "No folders",
        "Nenhuma tarefa ainda": "No tasks yet",
        "Nenhuma tarefa aqui": "No tasks here",
        "Nenhuma tarefa encontrada": "No tasks found",
        "Nome": "Name",
        "Nome da equipe": "Team name",
        "Nome da pasta": "Folder name",
        "Nome do participante": "Participant name",
        "Notas": "Notes",
        "Notas da conversa": "Conversation notes",
        "Notificações": "Notifications",
        "Notificações (%d)": "Notifications (%d)",
        "Nova Entrevista": "New Interview",
        "Nova conversa": "New conversation",
        "Nova equipe": "New team",
        "Nova nota": "New note",
        "Nova pasta": "New folder",
        "Nova tarefa": "New task",
        "Não iniciado": "To Do",
        "O áudio capturado até agora é descartado.": "The recorded audio so far will be discarded.",
        "OK": "OK",
        "Ocultar": "Hide",
        "Ocultar coluna %@": "Hide %@ column",
        "Ocultar seção %@": "Hide %@ section",
        "Ocultar tarefa": "Hide task",
        "Ocultas": "Hidden",
        "Ontem": "Yesterday",
        "Opções": "Options",
        "Ordenação": "Sort",
        "Organizar": "Organize",
        "Painel": "Panel",
        "Painel de Tarefas": "Tasks Board",
        "Participantes": "Participants",
        "Pasta": "Folder",
        "Pastas": "Folders",
        "Pausa": "Pause",
        "Pausado": "Paused",
        "Pausar": "Pause",
        "Pausar gravação": "Pause recording",
        "Perfil": "Profile",
        "Perfil pessoal": "Personal profile",
        "Personalização": "Customization",
        "Player": "Player",
        "Preencher": "Fill",
        "Preparando biblioteca": "Preparing library",
        "Preparando áudio": "Preparing audio",
        "Prioridade": "Priority",
        "Prioridade:": "Priority:",
        "Processamento": "Processing",
        "Processamento automático": "Automatic processing",
        "Processando": "Processing",
        "Processando conversa": "Processing conversation",
        "Pronto": "Ready",
        "Prévia": "Preview",
        "Próximos 7 dias": "Next 7 days",
        "Qwen": "Qwen",
        "Recolher": "Collapse",
        "Reconhecimento": "Recognition",
        "Reconhecimento de fala": "Speech recognition",
        "Recortar": "Trim",
        "Regras": "Rules",
        "Remover": "Remove",
        "Remover anexo": "Remove attachment",
        "Remover da equipe": "Remove from team",
        "Remover pessoa": "Remove person",
        "Renomear": "Rename",
        "Renomear falante": "Rename speaker",
        "Renomear pasta": "Rename folder",
        "Reproduzir": "Play",
        "Responsável": "Assignee",
        "Restaurar": "Restore",
        "Restaurar tamanho": "Restore size",
        "Resumo": "Summary",
        "Resumo da conversa": "Conversation summary",
        "Retomar": "Resume",
        "Retomar gravação": "Resume recording",
        "Reunião": "Meeting",
        "Reuniões": "Meetings",
        "Rótulo": "Label",
        "Sair": "Sign Out",
        "Salvar": "Save",
        "Salvar alterações": "Save changes",
        "Salvar informações": "Save details",
        "Segurança": "Security",
        "Selecionar": "Select",
        "Selecionar equipe": "Select team",
        "Sem data": "No date",
        "Sem deadline": "No deadline",
        "Sem responsável": "No assignee",
        "Sessão": "Session",
        "Seção recolhida — pode soltar aqui.": "Section collapsed — drop here.",
        "Sign in with Apple": "Sign in with Apple",
        "Silenciar": "Mute",
        "Sistema": "System",
        "Sobre": "About",
        "Sobre a gravação": "About recording",
        "Sobre esta tela": "About this screen",
        "Sobre o painel de tarefas": "About the tasks board",
        "Solte uma tarefa aqui para mudar para %@.": "Drop a task here to change to %@.",
        "Solte uma tarefa aqui.": "Drop a task here.",
        "Somado a partir dos nomes de Equipe e Externos.": "Combined from Team and External names.",
        "Status": "Status",
        "Sugestões": "Suggestions",
        "Sugestões da conversa": "Conversation suggestions",
        "Tabela": "Table",
        "Tamanho": "Size",
        "Tarefa": "Task",
        "Tarefas": "Tasks",
        "Tempo": "Time",
        "Tempo atual da gravação": "Current recording time",
        "Tempo decorrido": "Elapsed time",
        "Todas": "All",
        "Todas as conversas": "All conversations",
        "Todas as tarefas": "All tasks",
        "Todo": "All",
        "Todos": "All",
        "Transcrevendo…": "Transcribing…",
        "Transcrever": "Transcribe",
        "Transcrito": "Transcribed",
        "Transcrição": "Transcription",
        "Trocar…": "Change…",
        "Truncar": "Truncate",
        "Tudo": "All",
        "Título": "Title",
        "Título da conversa": "Conversation title",
        "Título da entrevista": "Interview title",
        "Upload": "Upload",
        "Usar": "Use",
        "Usar foto": "Use photo",
        "Velocidade": "Speed",
        "Vem da duração do áudio desta conversa.": "Based on this conversation's audio duration.",
        "Vence amanhã": "Due tomorrow",
        "Vence hoje": "Due today",
        "Visualização": "View",
        "Voltar": "Back",
        "Voltar para a biblioteca": "Back to library",
        "Voltar para a gravação em andamento": "Return to recording in progress",
        "Volume": "Volume",
        "Voz": "Voice",
        "Waveform": "Waveform",
        "Whisper": "Whisper",
        "conversas selecionadas": "selected conversations",
        "dd/mm/aaaa": "mm/dd/yyyy",
        "distinguindo falantes…": "distinguishing speakers…",
        "na fila (posição %d)": "in queue (position %d)",
        "obrigatório": "required",
        "ocultas": "hidden",
        "pendente": "pending",
        "pronto para transcrever": "ready to transcribe",
        "resolvendo falantes pelo contexto…": "resolving speakers from context…",
        "resumindo…": "summarizing…",
        "salvando…": "saving…",
        "traduzindo…": "translating…",
        "transcrevendo…": "transcribing…",
        "transcrito": "transcribed",
        "transcrito e resumido": "transcribed and summarized",
    ]
}
