import Foundation

/// Tabela canônica de traduções para Inglês US (regionalização integral).
/// Garante que todos os textos regionalizados resolvam com latência zero e 100% de confiabilidade.
public enum TabelaDeStrings: Sendable {
    public static let en: [String: String] = [
        "%@ cópia": "%@ copy",
        "%@ de %@": "%@ of %@",
        "%@ já está com transcrição e resumo prontos.": "%@ transcription and summary are ready.",
        "%@ não teve fala reconhecida.": "%@ had no recognized speech.",
        "%@ vence %@ e foi marcada como prioridade alta.": "%@ is due %@ and was marked as high priority.",
        "%@. %@": "%@. %@",
        "%d alteração(ões) aguardando nova tentativa no iCloud%@": "iCloud changes awaiting retry: %d%@",
        "%d alteração(ões) continuam na fila do iCloud.": "Pending iCloud operations: %d",
        "%d anexos não puderam ser apagados e continuam na lixeira.": "%d attachments could not be deleted and remain in Trash.",
        "%d arquivos": "%d files",
        "%d conversa(s) têm uma edição local pendente; a cópia local foi preservada até o próximo envio.": "Conversations with pending local edits: %d. Local copies are preserved until the next sync.",
        "%d conversas": "%d conversations",
        "%d conversas selecionadas": "%d conversations selected",
        "%d de %d": "%d of %d",
        "%d de %d membros": "%d of %d members",
        "%d membros": "%d members",
        "%d ocorrências": "%d occurrences",
        "%d participantes": "%d participants",
        "%d reunião(ões) com participantes — sincronizadas automaticamente na aba Calendário da biblioteca.": "Meetings with attendees: %d — automatically synced in the Library Calendar tab.",
        "%d reuniões": "%d meetings",
        "%d segundos": "%d seconds",
        ".": ".",
        "1 arquivo": "1 file",
        "1 conversa": "1 conversation",
        "1 membro": "1 member",
        "1 nota": "1 note",
        "1 ocorrência": "1 occurrence",
        "1 participante": "1 participant",
        "1 reunião": "1 meeting",
        "1 segundo": "1 second",
        "42 min": "42 min",
        "8 conversas": "8 conversations",
        ": %@": ": %@",
        "A biblioteca ainda está abrindo — a conexão com o Google Calendar aparece aqui em instantes.": "The library is still opening — Google Calendar connection will appear here shortly.",
        "A biblioteca ainda está abrindo — a conexão com o Granola aparece aqui em instantes.": "The library is still opening — Granola connection will appear here shortly.",
        "A biblioteca ainda não abriu.": "The library has not opened yet.",
        "A conversa saiu deste Mac, mas a remoção não entrou na fila do iCloud: %@": "Conversation was removed from this Mac, but deletion was not queued on iCloud: %@",
        "A entrada por código está ativa.": "Code access is active.",
        "A equipe foi aceita, mas o tipo de registro “Conversa” ainda não está publicado no CloudKit de produção. Peça ao proprietário da equipe para publicar o esquema no CloudKit Dashboard; suas alterações continuam neste Mac até isso acontecer.": "The team was accepted, but the “Conversa” record type is not yet deployed to the production CloudKit schema. Ask the team owner to deploy the schema in CloudKit Dashboard; your changes remain on this Mac until then.",
        "A exclusão ainda não pode ser concluída porque o tipo público “EquipeExcluida” não está publicado no CloudKit de produção. No CloudKit Dashboard, publique esse tipo e os campos equipeID, excluidaEm e estadoDaExclusao; nenhum dado foi apagado.": "Deletion cannot be completed because the public “EquipeExcluida” type is not deployed to the production CloudKit schema. In CloudKit Dashboard, deploy that type and the equipeID, excluidaEm, and estadoDaExclusao fields; no data was deleted.",
        "A gravação não estava na pasta esperada da biblioteca.": "Recording was not found in the expected library folder.",
        "A imagem cobre a cor. O texto do cartão ganha um véu escuro por cima dela para continuar legível.": "The image covers the color. Card text has a dark overlay to maintain readability.",
        "A lista vem diretamente do compartilhamento do iCloud. O CloudKit não disponibiliza os e-mails das Apple Accounts.": "The list comes directly from iCloud Sharing. CloudKit does not provide Apple Account emails.",
        "A lixeira está vazia": "Trash is empty",
        "A pasta %@ está vazia": "%@ is empty",
        "A pasta estava vazia. Restaure para tê-la de volta com a cor e a imagem que tinha.": "The folder was empty. Restore it to bring back its original color and image.",
        "A pasta ficará disponível para organizar conversas.": "The folder will be available to organize conversations.",
        "A pasta é só um rótulo. Nada mais será removido.": "The folder is just a label. Nothing else will be removed.",
        "A permissão do proprietário da equipe não pode ser alterada.": "The team owner's permission cannot be changed.",
        "A primeira conversa aparecerá aqui depois de gravar ou importar um áudio.": "Your first conversation will appear here after you record or import audio.",
        "A reunião %@ não foi encontrada no Google Calendar.": "Meeting %@ was not found in Google Calendar.",
        "A reunião %@ não foi encontrada no Granola.": "Meeting %@ was not found in Granola.",
        "A reunião %@ tem uma data inválida no Google Calendar.": "Meeting %@ has an invalid date in Google Calendar.",
        "A senha é gerenciada pelo seu ID Apple. Para alterar, use os ajustes da sua conta Apple.": "Password is managed by your Apple ID. To change it, use your Apple Account settings.",
        "A sessão expirou e não há refresh token. Conecte de novo.": "The session expired and no refresh token is available. Connect again.",
        "A sessão expirou e o Ōmu não tem como renová-la. Conecte de novo.": "The session expired and Ōmu cannot renew it. Connect again.",
        "A transcrição aparecerá aqui conforme o áudio for processado.": "Transcription will appear here as audio is processed.",
        "A transcrição aparecerá depois do processamento.": "Transcription will appear after processing.",
        "A transcrição falhou": "Transcription failed",
        "A transcrição, as notas e o resumo continuam aqui. Restaure o áudio pela Lixeira do app — assim ele volta com o nome que a reprodução espera.": "Transcript, notes, and summary remain here. Restore audio from Trash to keep playback intact.",
        "A versão instalada ainda tenta consultar o tipo de registro “Conversa”, mas ele não está indexado no CloudKit. Atualize o Ōmu para a versão que sincroniza diretamente a zona compartilhada; suas alterações locais permanecem neste Mac.": "This version still tries to query the “Conversa” record type, but it is not indexed in CloudKit. Update Ōmu to the version that syncs the shared zone directly; your local changes remain on this Mac.",
        "A zona compartilhada desta equipe ainda não está disponível nesta Apple Account. Peça ao proprietário para confirmar o compartilhamento e entre novamente com o código da equipe.": "This team's shared zone is not yet available to this Apple Account. Ask the owner to confirm sharing, then join again with the team code.",
        "A zona do CloudKit, as conversas compartilhadas e os dados deste Mac serão apagados. Outros Macs atualizados removem suas cópias ao se conectarem ao iCloud. Esta ação não pode ser desfeita.": "The CloudKit zone, shared conversations, and local data on this Mac will be deleted. This action cannot be undone.",
        "ACESSO": "ACCESS",
        "AO VIVO": "LIVE",
        "ARQUIVO": "FILE",
        "Abre o navegador do macOS para autorizar o Ōmu na sua conta do Granola.": "Opens your browser to authorize Ōmu with your Granola account.",
        "Abre o navegador para autorizar o Ōmu na sua conta Google.": "Opens your browser to authorize Ōmu with your Google account.",
        "Abrir": "Open",
        "Abrir a pasta %@": "Open %@ folder",
        "Abrir no app": "Open in app",
        "Abrir pasta": "Open folder",
        "Aceitar e mandar para o quadro": "Accept and send to board",
        "Acesso": "Access",
        "Acesso e exclusão": "Access & Deletion",
        "Acompanha o ajuste de aparência do seu Mac.": "Matches your Mac's appearance setting.",
        "Adiciona esta conversa à fila. O resumo será feito após a transcrição.": "Adds this conversation to queue. Summary will be generated after transcription.",
        "Adicionar": "Add",
        "Adicionar mídia": "Add media",
        "Adicionar nova equipe": "Add new team",
        "Adicionar participante": "Add participant",
        "Adicionar pasta": "Add folder",
        "Adicionar pessoa": "Add person",
        "Adicionar tarefa": "Add task",
        "Adicionar uma pasta": "Add a folder",
        "Adicione uma descrição": "Add a description",
        "Administrador": "Administrator",
        "Aguardando": "Waiting",
        "Aguardando download": "Waiting for download",
        "Aguardando modelos": "Waiting for models",
        "Aguardando transcrição": "Waiting for transcription",
        "Aguardar revisão": "Wait for review",
        "Ajustar": "Fit",
        "Ajustar capa": "Adjust cover",
        "Ajustes": "Settings",
        "Alinhamento dos Falantes": "Speaker Alignment",
        "Alta": "High",
        "Alterar Senha": "Change Password",
        "Alterar permissão": "Change permission",
        "Alternar": "Toggle",
        "Amanhã": "Tomorrow",
        "Ana Silva": "Jane Doe",
        "Anexo": "Attachment",
        "Anexo removido da mídia de %@. Restaure para voltar à aba Mídia dessa conversa.": "Attachment removed from %@ media. Restore to return it to the Media tab.",
        "Anexos": "Attachments",
        "Anexos de Mídia": "Media Attachments",
        "Ao finalizar, a conversa será salva na biblioteca.": "When finished, conversation will be saved to library.",
        "Apaga as credenciais do Google Calendar do Keychain.": "Deletes Google Calendar credentials from Keychain.",
        "Apaga as credenciais do Granola do Keychain.": "Deletes Granola credentials from Keychain.",
        "Apagado em %@": "Deleted on %@",
        "Apagar": "Delete",
        "Apagar %@ definitivamente?": "Delete %@ permanently?",
        "Apagar a pasta %@?": "Delete folder %@?",
        "Apagar anexo": "Delete attachment",
        "Apagar anexo definitivamente?": "Delete attachment permanently?",
        "Apagar de vez": "Delete permanently",
        "Apagar definitivamente": "Delete permanently",
        "Apagar definitivamente %@": "Delete %@ permanently",
        "Apagar definitivamente a pasta %@": "Delete folder %@ permanently",
        "Apagar definitivamente todos os arquivos da lixeira": "Delete all files in trash permanently",
        "Apagar definitivamente?": "Delete permanently?",
        "Apagar nota": "Delete note",
        "Apagar pasta": "Delete folder",
        "Apagar perfil": "Delete profile",
        "Apagar tarefa definitivamente": "Delete task permanently",
        "Aparência": "Appearance",
        "Aparência %@": "Appearance %@",
        "Aparência do app, os cartões da biblioteca e quando as transcrições começam.": "App appearance, library cards, and when transcriptions begin.",
        "Aparência dos Cards": "Card Appearance",
        "Apenas no Mac": "On Mac only",
        "Apple Account compartilhada": "Shared Apple Account",
        "Arquivo": "File",
        "Arquivo colado": "Pasted file",
        "Arquivo importado": "Imported file",
        "Arquivo importado: um canal só, sem separação de falante.": "Imported file: single channel, without speaker separation.",
        "Arquivos": "Files",
        "Arquivos movidos da biblioteca aparecerão aqui e poderão ser recuperados.": "Files moved from the library appear here and can be recovered.",
        "Arraste tarefas para cá": "Drag tasks here",
        "Arraste uma tarefa para cá": "Drag a task here",
        "As %d conversas continuam na biblioteca — só deixam de estar nesta pasta.": "%d conversations remain in your library — they simply leave this folder.",
        "As notas também foram descartadas porque a gravação era curta demais para criar um arquivo.": "Notes were also discarded because the recording was too short to create a file.",
        "Atalhos": "Shortcuts",
        "Atalhos da biblioteca": "Library shortcuts",
        "Atalhos de teclado": "Keyboard shortcuts",
        "Atenção": "Warning",
        "Atividade": "Activity",
        "Ativo": "Active",
        "Atrasada": "Overdue",
        "Atrasadas": "Overdue",
        "Atualizando": "Updating",
        "Atualizando arquivo na lixeira": "Updating file in trash",
        "Atualizar": "Update",
        "Atualize os dados que aparecem no card e no cabeçalho.": "Update the information shown on the card and header.",
        "Autorização cancelada ou recusada no navegador.": "Authorization was canceled or declined in the browser.",
        "Autorização concluída": "Authorization complete",
        "Autorização recusada": "Authorization declined",
        "Autorize no navegador e volte ao Ōmu…": "Authorize in browser and return to Ōmu…",
        "Autorize o microfone em Ajustes do Sistema › Privacidade › Microfone.": "Allow microphone access in System Settings › Privacy › Microphone.",
        "Autorize o reconhecimento de fala em Ajustes do Sistema › Privacidade.": "Allow speech recognition in System Settings › Privacy.",
        "Avançar 10 segundos": "Forward 10 seconds",
        "AÇÕES": "ACTIONS",
        "Ações": "Actions",
        "Ações da pasta": "Folder actions",
        "Ações da tarefa": "Task actions",
        "Ações de %@": "Actions for %@",
        "Ações do card": "Card actions",
        "Baixa": "Low",
        "Baixando": "Downloading",
        "Baixando modelos…": "Downloading models…",
        "Baixar": "Download",
        "Baixar modelos (%@)": "Download models (%@)",
        "Biblioteca": "Library",
        "Biblioteca de Conversas": "Conversation Library",
        "Biblioteca de Conversas (Pastas)": "Conversation Library (Folders)",
        "Biblioteca de conversas": "Conversation library",
        "Buscar": "Search",
        "Buscar conversas…": "Search conversations…",
        "Buscar mídias…": "Search media…",
        "Buscar na lixeira…": "Search trash…",
        "Buscar tarefas…": "Search tasks…",
        "Cabeçalho": "Header",
        "Cada nota fica presa a um instante. Clique no tempo para ouvir o trecho, e use #etiquetas para agrupar depois.": "Each note is pinned to a timestamp. Click the time to listen, and use #tags to group later.",
        "Calendário": "Calendar",
        "Campo obrigatório": "Required field",
        "Canal misto ou desconhecido": "Mixed or unknown channel",
        "Cancelar": "Cancel",
        "Cancelar a gravação?": "Cancel recording?",
        "Cancelar gravação": "Cancel recording",
        "Cancelar o processamento e mover para a lixeira": "Cancel processing and move to trash",
        "Cancelar processamento": "Cancel processing",
        "Capa": "Cover",
        "Card": "Card",
        "Carregando participantes…": "Loading participants…",
        "Carregando reuniões…": "Loading meetings…",
        "Carregando…": "Loading…",
        "Cartões da biblioteca": "Library cards",
        "Claro": "Light",
        "Client ID do Google não configurado. Configure-o no arquivo local do projeto.": "Google Client ID is not configured. Set it in the project's local configuration file.",
        "Client ID/Secret não configurados": "Client ID/Secret not configured",
        "Clique ou arraste do Finder": "Click or drag from Finder",
        "Clique para ver a conversa": "Click to view conversation",
        "Clique para voltar à tela de gravação.": "Click to return to recording screen.",
        "Coluna recolhida — pode soltar aqui.": "Column collapsed — drop here.",
        "Como funciona o Google Calendar": "How Google Calendar works",
        "Como funciona o Granola": "How Granola works",
        "Como funciona o microfone": "How microphone works",
        "Como funciona o processamento": "How processing works",
        "Como funcionam as notas": "How notes work",
        "Como funcionam os modelos": "How models work",
        "Compartilhado": "Shared",
        "Compartilhamento": "Sharing",
        "Compartilhamentos no iCloud": "iCloud Shares",
        "Compartilhar": "Share",
        "Compartilhar conversa": "Share conversation",
        "Compartilhe este código com quem deve entrar. Ao informá-lo no Ōmu, a pessoa recebe acesso de leitura e escrita à equipe nesta Apple Account.": "Share this code with people who need to join. Entering it in Ōmu gives them read and write access to this team with their Apple Account.",
        "Compartilhe o código para dar acesso ao espaço compartilhado.": "Share the code to grant access to the shared space.",
        "Concluir": "Complete",
        "Concluir edição": "Finish editing",
        "Concluir gravação": "Finish recording",
        "Concluída": "Completed",
        "Concluídas": "Completed",
        "Concluído": "Completed",
        "Conectado": "Connected",
        "Conectado ao Google Calendar": "Connected to Google Calendar",
        "Conectado ao Granola": "Connected to Granola",
        "Conectado, o Ōmu pode ver suas reuniões do Granola e importá-las para a biblioteca — notas e resumo sempre; a transcrição quando o seu plano incluir. Nada é enviado para fora do seu Mac além do fluxo de autorização e das chamadas ao próprio Granola.": "Once connected, Ōmu can view your Granola meetings and import them into the library — always with notes and a summary, and with a transcript when your plan includes it. Nothing leaves your Mac except the authorization flow and calls to Granola.",
        "Conectado, o Ōmu pode ver suas reuniões futuras do Google Calendar e importá-las para a biblioteca — apenas título, data e participantes. Nada é enviado para fora do seu Mac além do fluxo de autorização e das chamadas ao próprio Google.": "Connected, Ōmu can view upcoming Google Calendar meetings and import title, date, and attendees locally. Nothing leaves your Mac.",
        "Conectar": "Connect",
        "Conectar conta Google…": "Connect Google account…",
        "Conectar conta Granola…": "Connect Granola account…",
        "Conexões": "Connections",
        "Confiança %.0f%% — baixa": "Confidence %.0f%% — low",
        "Configurações": "Settings",
        "Configurações da equipe": "Team settings",
        "Configure os detalhes da sua nova sessão": "Configure your new session details",
        "Confirmar": "Confirm",
        "Confirmar exclusão": "Confirm deletion",
        "Conflito de sincronização": "Sync conflict",
        "Conta": "Account",
        "Conta ativa": "Active account",
        "Conta ativa: %@": "Active account: %@",
        "Conta pessoal": "Personal account",
        "Conta proprietária": "Owner account",
        "Continuar": "Resume",
        "Continuar gravando": "Keep recording",
        "Continuar gravação": "Resume recording",
        "Conversa": "Conversation",
        "Conversa %@. %@": "Conversation %@. %@",
        "Conversa movida para a lixeira. Restaure para acessar transcrição, notas e mídia.": "Conversation moved to Trash. Restore it to access the transcript, notes, and media.",
        "Conversa salva só neste Mac": "Conversation saved on this Mac only",
        "Conversas": "Conversations",
        "Conversas recentes": "Recent conversations",
        "Convite pendente": "Invitation pending",
        "Copiar": "Copy",
        "Copiar conversa inteira": "Copy entire conversation",
        "Copiar código": "Copy code",
        "Copiar link": "Copy link",
        "Copiar texto": "Copy text",
        "Cor": "Color",
        "Cor de destaque": "Accent color",
        "Cor e imagem": "Color and image",
        "Cor padrão": "Default color",
        "Corrigir o texto desta fala": "Correct this speaker's text",
        "Corrigir o texto deste trecho": "Correct this passage",
        "Corrija a nota…": "Edit note…",
        "Criar": "Create",
        "Criar e mover": "Create and move",
        "Criar equipe": "Create team",
        "Criar nova pasta": "Create new folder",
        "Criar nova pasta…": "Create new folder…",
        "Criar pasta": "Create folder",
        "Criar pasta e mover": "Create folder and move",
        "Criar tarefa": "Create task",
        "Crie uma equipe ou entre com um código no seu perfil.": "Create a team or join one with a code in your profile.",
        "Crie uma equipe para vincular ao seu perfil.": "Create a team to link to your profile.",
        "Crie uma pasta nova e esta conversa será movida para ela.": "Create a new folder and this conversation will be moved into it.",
        "Código": "Code",
        "Código da equipe": "Team code",
        "Código de convite": "Invite code",
        "Código de entrada": "Join code",
        "Código indisponível para equipes criadas antes desta atualização.": "Codes are unavailable for teams created before this update.",
        "Dados locais": "Local data",
        "Data": "Date",
        "Data da entrevista": "Interview date",
        "Data de criação": "Creation date",
        "Data de entrega": "Due date",
        "Data de modificação": "Modification date",
        "Data e hora": "Date & Time",
        "Data e hora da reunião": "Meeting date & time",
        "Data limite": "Due date",
        "Data não reconhecida. Use %@.": "Unrecognized date. Use %@.",
        "Data não reconhecida. Use dd/mm/aaaa.": "Unrecognized date. Use mm/dd/yyyy.",
        "Datas da conversa": "Conversation dates",
        "Deadline": "Deadline",
        "Deadline perto: a tarefa será marcada como prioridade alta.": "Due soon: this task will be marked high priority.",
        "Defina título, responsável, prioridade e deadline antes de salvar.": "Set a title, assignee, priority, and due date before saving.",
        "Deixar equipe": "Leave team",
        "Deixar esta equipe?": "Leave this team?",
        "Deletar": "Delete",
        "Descartar": "Discard",
        "Descartar sugestão": "Discard suggestion",
        "Desconectar": "Disconnect",
        "Desconectar conta Google": "Disconnect Google account",
        "Desconectar conta Granola": "Disconnect Granola account",
        "Descrição": "Description",
        "Descrição da reunião": "Meeting description",
        "Descrição da tarefa": "Task description",
        "Desfavoritar": "Remove from Favorites",
        "Desmarcar %@": "Deselect %@",
        "Destino": "Destination",
        "Detalhes": "Details",
        "Detalhes da conversa": "Conversation details",
        "Detalhes, contexto ou o que precisa ser feito": "Details, context, or what needs to be done",
        "Diarização": "Diarization",
        "Diarização de falantes": "Speaker Diarization",
        "Diarização local": "Local Diarization",
        "Digite a data": "Enter date",
        "Digite o nome da pasta": "Enter folder name",
        "Dispensar": "Dismiss",
        "Dispensar mensagem de erro": "Dismiss error message",
        "Disponível depois que o resumo estiver pronto": "Available once summary is ready",
        "Distinguir falantes": "Distinguish speakers",
        "Ditar nota": "Dictate note",
        "Dono": "Owner",
        "Duplicar": "Duplicate",
        "Duração": "Duration",
        "Duração da conversa": "Conversation duration",
        "Duração da gravação": "Recording duration",
        "Duração total": "Total duration",
        "Dê um nome de verdade a cada voz identificada pela diarização. Isso atualiza todas as falas dela na transcrição de uma vez.": "Give each diarized voice a real name. This updates all of their dialogue in the transcript at once.",
        "E-mail": "Email",
        "E-mail do entrevistado": "Interviewee email",
        "E-mail dos entrevistadores": "Interviewers email",
        "Editar": "Edit",
        "Editar antes de aceitar": "Edit before accepting",
        "Editar informações": "Edit details",
        "Editar nome": "Edit name",
        "Editar nota": "Edit note",
        "Editar pasta": "Edit folder",
        "Editar tarefa": "Edit task",
        "Editar título e descrição": "Edit title and description",
        "Editar…": "Edit…",
        "Ela vai para a lixeira, de onde dá para restaurar depois.": "It moves to Trash, where you can restore it later.",
        "Elementos": "Elements",
        "Em andamento": "In Progress",
        "Email Primário": "Primary email",
        "Enter salva · Enter vazio marca o instante": "Enter saves · Empty Enter bookmarks timestamp",
        "Entrada por código": "Code access",
        "Entrar": "Sign in",
        "Entrar automaticamente": "Join automatically",
        "Entrar com Apple": "Sign in with Apple",
        "Entrar com código": "Join with code",
        "Entrar em uma equipe": "Join a team",
        "Entrar na equipe": "Join team",
        "Entrar por código": "Join via code",
        "Entre no iCloud neste Mac para usar equipes compartilhadas.": "Sign in to iCloud on this Mac to use shared teams.",
        "Entrevista": "Interview",
        "Entrevista com Ana Silva": "Interview with Jane Doe",
        "Entrevistada": "Interviewee",
        "Entrevistadas": "Interviewees",
        "Entrevistado": "Interviewee",
        "Entrevistado não informado": "Interviewee not specified",
        "Entrevistador": "Interviewer",
        "Entrevistador não informado": "Interviewer not specified",
        "Entrevistadora": "Interviewer",
        "Entrevistadoras": "Interviewers",
        "Entrevistadores": "Interviewers",
        "Entrevistados": "Interviewees",
        "Equipe": "Team",
        "Equipes": "Teams",
        "Erro": "Error",
        "Erro ao carregar": "Error loading",
        "Erro ao conectar": "Connection error",
        "Erro ao excluir": "Deletion error",
        "Erro ao exportar": "Export error",
        "Erro ao importar": "Import error",
        "Erro ao salvar": "Error saving",
        "Erro de transcrição": "Transcription error",
        "Erro do Keychain (%d).": "Keychain error (%d).",
        "Escola / Trabalho": "School / Work",
        "Escolha a conversa, descreva a tarefa e defina prioridade, responsável e data limite.": "Choose conversation, describe task, and set priority, assignee, and due date.",
        "Escolha em qual equipe você quer trabalhar agora.": "Choose which team you want to work in now.",
        "Escolha fotos, vídeos, áudios, PDFs ou outros arquivos para salvar nesta conversa.": "Choose photos, videos, audio, PDFs, or other files to save in this conversation.",
        "Escolha o arquivo de áudio da reunião": "Choose meeting audio file",
        "Escolha o que aparece nos cartões da biblioteca. Vale para todos.": "Choose what appears on library cards. Applies to all.",
        "Escolha onde salvar %@": "Choose where to save %@",
        "Escolha onde salvar a pasta %@": "Choose where to save folder %@",
        "Escolha uma foto para %@": "Choose a photo for %@",
        "Escolha uma imagem para a faixa": "Choose an image for banner",
        "Escolha uma imagem para a pasta": "Choose an image for the folder",
        "Escolher arquivo": "Choose file",
        "Escolher conversa": "Choose conversation",
        "Escolher foto do perfil": "Choose profile photo",
        "Escolher participante": "Choose participant",
        "Escolher pasta…": "Choose folder…",
        "Escolher…": "Choose…",
        "Esconder de novo as tarefas ocultas": "Hide hidden tasks again",
        "Escreva e pressione Enter…": "Write and press Enter…",
        "Escreva no campo acima e pressione Enter. O instante do áudio fica guardado junto.": "Type in the field above and press Return. The audio timestamp is saved with it.",
        "Escreva o nome primeiro": "Enter a name first",
        "Escreva uma nota e pressione Enter…": "Write a note and press Enter…",
        "Escuro": "Dark",
        "Espaço local": "Local space",
        "Essa Apple Account não poderá mais ler nem alterar as conversas da equipe.": "This Apple Account will no longer be able to read or modify team conversations.",
        "Essa ação remove o áudio, a transcrição e o resumo do Mac e não pode ser desfeita.": "This removes the audio, transcript, and summary from your Mac and cannot be undone.",
        "Essa ação remove permanentemente todos os arquivos da lixeira e não pode ser desfeita.": "This permanently removes every file from Trash and cannot be undone.",
        "Esse membro não faz mais parte do compartilhamento.": "This member is no longer part of the share.",
        "Esta ação não pode ser desfeita. Seu perfil, conversas pessoais, áudios, transcrições, notas, tarefas, vínculos de equipe e conexões com Google Calendar e Granola serão removidos deste Mac. Os dados dos espaços de equipe, as preferências do app e os compartilhamentos do iCloud serão preservados.": "This action cannot be undone. Your profile, personal conversations, audio, transcripts, notes, tasks, and integrations will be removed from this Mac.",
        "Esta equipe ainda não foi publicada no CloudKit.": "This team has not been published to CloudKit yet.",
        "Esta pasta não contém conversas para exportar.": "This folder has no conversations to export.",
        "Estas preferências são compartilhadas no iCloud. A política de revisão de recebimento será aplicada ao fluxo de arquivos em uma próxima etapa; ainda não bloqueia automaticamente envios.": "These preferences are shared in iCloud. The file review policy will be applied in a future step; it does not automatically block uploads yet.",
        "Este nome será exibido para todas as pessoas desta equipe.": "This name will be displayed to everyone on this team.",
        "Esvaziar Lixeira": "Empty Trash",
        "Esvaziar lixeira": "Empty trash",
        "Esvaziar lixeira?": "Empty Trash?",
        "Eu": "Me",
        "Eu · microfone": "Me · microphone",
        "Evento sem título": "Untitled event",
        "Ex.: Ana Silva": "e.g., Ana Silva",
        "Ex.: Entrevista com Stakeholders - UX Research": "e.g., Stakeholder Interview - UX Research",
        "Ex.: João Santos": "e.g., João Santos",
        "Ex.: Revisar documentação": "e.g., Review documentation",
        "Ex.: Revisar pontos da entrevista": "e.g., Review interview points",
        "Exclui em %d dias": "Deletes in %d days",
        "Exclui em 1 dia": "Deletes in 1 day",
        "Exclui em 30 dias": "Deletes in 30 days",
        "Exclui hoje": "Deletes today",
        "Excluindo...": "Deleting…",
        "Excluir": "Delete",
        "Excluir da equipe": "Remove from team",
        "Excluir equipe": "Delete team",
        "Excluir equipe e dados": "Delete team and data",
        "Excluir esta conversa?": "Delete this conversation?",
        "Excluir esta equipe para todos?": "Delete this team for everyone?",
        "Excluir esta pasta?": "Delete this folder?",
        "Excluir esta tarefa?": "Delete this task?",
        "Excluir perfil": "Delete profile",
        "Excluir perfil deste Mac?": "Delete this profile from this Mac?",
        "Excluir perfil e dados pessoais": "Delete profile and personal data",
        "Excluir reunião": "Delete meeting",
        "Exemplo": "Example",
        "Exibir ficha automaticamente": "Show details sheet automatically",
        "Exibir ficha automaticamente após processar": "Show details automatically after processing",
        "Exportado com sucesso": "Exported successfully",
        "Exportando…": "Exporting…",
        "Exportar": "Export",
        "Exportar Markdown": "Export Markdown",
        "Exportar com áudio": "Export with audio",
        "Exportar áudio": "Export audio",
        "Externos": "External",
        "Falante": "Speaker",
        "Falante %@": "Speaker %@",
        "Falante %d": "Speaker %d",
        "Falantes": "Speakers",
        "Fale — o texto aparece aqui.": "Start speaking — text appears here.",
        "Falha ao carregar": "Failed to load",
        "Falha ao iniciar servidor local para OAuth: %@": "Could not start the local OAuth server: %@",
        "Falha ao remover do iCloud": "Could not remove from iCloud",
        "Falha ao salvar": "Failed to save",
        "Falha de sincronização do iCloud": "iCloud sync failed",
        "Falha na fila do iCloud": "iCloud queue failed",
        "Falha no processamento": "Processing failed",
        "Falta um modelo na pasta escolhida. Complete a pasta ou volte a usar a pasta do app para baixar.": "A model is missing from the selected folder. Complete the folder or switch back to the app folder to download it.",
        "Favoritar": "Add to Favorites",
        "Favorite uma conversa pelo botão de estrela para ela aparecer aqui.": "Favorite a conversation with the star button to show it here.",
        "Favoritos": "Favorites",
        "Fechar": "Close",
        "Fechar (Esc)": "Close (Esc)",
        "Fechar sem salvar": "Close without saving",
        "Ficha": "Details",
        "Ficha da conversa": "Conversation sheet",
        "Ficha da entrevista": "Interview details",
        "Fila de processamento": "Processing queue",
        "Filtro": "Filter",
        "Filtros": "Filters",
        "Finalizar": "Finish",
        "Finalizar gravação": "End recording",
        "Formato": "Format",
        "Formato de áudio": "Audio format",
        "Foto": "Photo",
        "Foto de %@": "Photo of %@",
        "Foto, vídeo, áudio ou arquivo": "Photo, video, audio, or file",
        "Foto, vídeo, áudio ou arquivo. Também aceita arrastar do Finder.": "Photo, video, audio, or file. Dragging from Finder is also supported.",
        "Fotos, vídeos, áudios e outros anexos de todas as conversas, reunidos num só lugar.": "Photos, videos, audio, and attachments from all conversations in one place.",
        "Fotos, vídeos, áudios e outros anexos salvos em qualquer conversa aparecerão reunidos aqui.": "Photos, videos, audio, and attachments saved in any conversation will appear here.",
        "Fotos, vídeos, áudios, documentos e anexos salvos nesta conversa.": "Photos, videos, audio, documents, and attachments saved in this conversation.",
        "Gera um novo resumo a partir da transcrição atual, sem re-transcrever": "Generates a new summary from current transcript without re-transcribing",
        "Geral": "General",
        "Gerando novo resumo…": "Generating new summary…",
        "Gerar nova conversa": "Generate new conversation",
        "Gerar novo resumo": "Generate new summary",
        "Gerenciada pelo ID Apple": "Managed by Apple ID",
        "Gerenciar": "Manage",
        "Gerenciar equipe": "Manage team",
        "Gerenciar perfil": "Manage profile",
        "Gerencie as tarefas geradas a partir das suas conversas.": "Manage tasks generated from your conversations.",
        "Gerencie conversas excluídas. Itens na lixeira serão removidos permanentemente após 30 dias.": "Manage deleted conversations. Items in trash will be permanently removed after 30 days.",
        "Gerencie suas pastas de conversas.": "Manage your conversation folders.",
        "Gerencie suas transcrições e insights de conversas.": "Manage your transcripts and conversation insights.",
        "Google Calendar": "Google Calendar",
        "Grade": "Grid",
        "Granola": "Granola",
        "Gravado": "Recorded",
        "Gravado em": "Recorded on",
        "Gravado em %@": "Recorded on %@",
        "Gravado em %@ · Importado em %@": "Recorded on %@ · Imported on %@",
        "Gravando": "Recording",
        "Gravando agora": "Recording now",
        "Gravar": "Record",
        "Gravar microfone": "Record microphone",
        "Gravar áudio do sistema": "Record system audio",
        "Gravação": "Recording",
        "Gravação ativa": "Active recording",
        "Gravação cancelada — nenhum arquivo foi criado.": "Recording canceled — no file was created.",
        "Gravação de %@": "Recording from %@",
        "Gravação descartada": "Recording discarded",
        "Gravação em andamento": "Recording in progress",
        "Gravação finalizada": "Recording completed",
        "Gravação pausada": "Recording paused",
        "Gravações": "Recordings",
        "Gravações e anexos ficarão prontos para transcrever. Você inicia o processamento pela aba Transcrição.": "Recordings and attachments will be ready to transcribe. Start processing from the Transcript tab.",
        "Grave áudio, importe um arquivo ou arraste aqui do Finder.": "Record audio, import a file, or drag one here from Finder.",
        "Grave, transcreva e revise suas conversas.": "Record, transcribe, and review your conversations.",
        "Grave, transcreva e revise suas conversas. O áudio fica no seu Mac, e a transcrição começa assim que você finalizar.": "Record, transcribe, and review your conversations. Audio stays on your Mac, and transcription begins as soon as you finish.",
        "Histórico": "History",
        "Hoje": "Today",
        "Hora": "Time",
        "IDENTIDADE": "IDENTITY",
        "Identidade": "Identity",
        "Identidade visual": "Visual identity",
        "Identificadas automaticamente na transcrição. Aceite para mandar para o quadro de tarefas, edite antes de aceitar ou descarte.": "Automatically identified in transcript. Accept to send to board, edit before accepting, or discard.",
        "Idioma": "Language",
        "Ignorar": "Ignore",
        "Imagem": "Image",
        "Imagem colada": "Pasted image",
        "Importa as reuniões marcadas para a biblioteca.": "Imports selected meetings into the library.",
        "Importado": "Imported",
        "Importado em": "Imported on",
        "Importado em %@": "Imported on %@",
        "Importado para o app em %@": "Imported into the app on %@",
        "Importados": "Imported",
        "Importar": "Import",
        "Importar selecionadas": "Import selected",
        "Importar áudio": "Import audio",
        "Importação concluída": "Import completed",
        "Importação falhou": "Import failed",
        "Importe reuniões do Granola para a biblioteca, com transcrição quando o plano permitir.": "Import Granola meetings into the library, with transcripts when your plan allows.",
        "Importe reuniões futuras do Google Calendar para a biblioteca.": "Import upcoming Google Calendar meetings into the library.",
        "Informações": "Information",
        "Informações Pessoais": "Personal Information",
        "Informações da Conta": "Account Information",
        "Informações da pasta": "Folder details",
        "Informações da reunião": "Meeting details",
        "Informe um nome para mostrar na equipe.": "Enter a name to display in the team.",
        "Inglês (US)": "English (US)",
        "Inicia a reprodução a partir de %@.": "Starts playback at %@.",
        "Iniciais": "Initials",
        "Iniciar gravação": "Start recording",
        "Iniciar sessão com Apple": "Sign in with Apple",
        "Inicie a transcrição quando quiser. O resumo será gerado em seguida, respeitando a fila de processamento.": "Start transcription whenever you are ready. The summary will follow, respecting the processing queue.",
        "Insira o código da equipe": "Enter team code",
        "Integrar": "Integrate",
        "Integrações": "Integrations",
        "Inteligência e Modelos": "Intelligence & Models",
        "Interlocutor · áudio do sistema": "Other speaker · system audio",
        "Itens na lixeira": "Items in trash",
        "Janela": "Window",
        "Janela flutuante": "Floating window",
        "João Santos": "John Smith",
        "Já usava esta equipe antes do acesso por código?": "Were you already using this team before code access?",
        "Layout": "Layout",
        "Legenda": "Caption",
        "Leitura e escrita": "Read and write",
        "Limite de tempo": "Time limit",
        "Limpar": "Clear",
        "Limpar busca": "Clear search",
        "Limpar seleção": "Clear selection",
        "Limpar tudo": "Clear all",
        "Linha do tempo": "Timeline",
        "Lista": "List",
        "Lixeira": "Trash",
        "Localização": "Localization",
        "Login com Apple": "Sign in with Apple",
        "MEMBRO": "MEMBER",
        "Mais antigas primeiro": "Oldest first",
        "Mais ações": "More actions",
        "Mais recentes primeiro": "Newest first",
        "Mantém o app claro, mesmo com o Mac no escuro.": "Keeps the app light, even when your Mac is in dark mode.",
        "Mantém o app escuro, mesmo com o Mac no claro.": "Keeps the app dark, even when your Mac is in light mode.",
        "Marcador": "Bookmark",
        "Marcar %@": "Select %@",
        "Marcar como em andamento": "Mark as in progress",
        "Medidor de áudio": "Audio meter",
        "Membro": "Member",
        "Membro da equipe": "Team member",
        "Membro desde %@": "Member since %@",
        "Membros": "Members",
        "Membros da equipe": "Team members",
        "Mensagem": "Message",
        "Menu": "Menu",
        "Meu Perfil": "My Profile",
        "Meu perfil": "My profile",
        "Microfone": "Microphone",
        "Microfone e Áudio": "Microphone & Audio",
        "Minhas reuniões": "My meetings",
        "Minimizar": "Minimize",
        "Modalidade": "Format",
        "Modalidade não informada": "Format not specified",
        "Modelo %@": "Model %@",
        "Modelo de transcrição": "Transcription model",
        "Modelo do cartão": "Card template",
        "Modelos": "Models",
        "Modelos de diarização não estagiados. Rode Scripts/bootstrap-runtimes.sh.": "Diarization models missing. Run Scripts/bootstrap-runtimes.sh.",
        "Modelos locais": "Local models",
        "Modo": "Mode",
        "Mostrar": "Show",
        "Mostrar %@": "Show %@",
        "Mostrar %@ no Finder": "Show %@ in Finder",
        "Mostrar as tarefas ocultas": "Show hidden tasks",
        "Mostrar coluna %@": "Show %@ column",
        "Mostrar confiança": "Show confidence",
        "Mostrar no Finder": "Show in Finder",
        "Mostrar painel flutuante durante a gravação": "Show floating panel during recording",
        "Mostrar porcentagem de confiança": "Show confidence percentage",
        "Mostrar seção %@": "Show %@ section",
        "Mostrar tarefa": "Show task",
        "Mova o arquivo para a lixeira antes de apagá-lo definitivamente.": "Move the file to Trash before deleting it permanently.",
        "Movendo para a lixeira…": "Moving to Trash…",
        "Mover": "Move",
        "Mover para Lixeira": "Move to Trash",
        "Mover para a lixeira": "Move to trash",
        "Mover para pasta": "Move to folder",
        "Mover para…": "Move to…",
        "Mover todos para a lixeira": "Move all to trash",
        "Mudar": "Switch",
        "Mudar Equipe": "Switch team",
        "Mudar cor": "Change color",
        "Mudar papel": "Change role",
        "Média": "Medium",
        "Mídia": "Media",
        "Mídias": "Media",
        "NOTA": "NOTE",
        "Na pasta %@": "In %@",
        "Nada aqui": "Nothing here",
        "Nada com esse filtro": "No results for this filter",
        "Nenhum anexo": "No attachments",
        "Nenhum arquivo": "No files",
        "Nenhum arquivo encontrado": "No files found",
        "Nenhum aviso ainda.": "No notifications yet.",
        "Nenhum favorito ainda": "No favorites yet",
        "Nenhum informado": "None specified",
        "Nenhum membro": "No members",
        "Nenhum membro encontrado": "No members found",
        "Nenhum microfone disponível.": "No microphone available.",
        "Nenhum participante": "No participants",
        "Nenhum participante encontrado": "No participants found",
        "Nenhum resultado": "No results",
        "Nenhuma conversa": "No conversations",
        "Nenhuma conversa encontrada": "No conversations found",
        "Nenhuma equipe ainda": "No teams yet",
        "Nenhuma fala reconhecida neste áudio.": "No speech was recognized in this audio.",
        "Nenhuma mídia ainda": "No media yet",
        "Nenhuma mídia encontrada": "No media found",
        "Nenhuma nota": "No notes",
        "Nenhuma nota ainda": "No notes yet",
        "Nenhuma pasta": "No folders",
        "Nenhuma reunião acessível nesta conta.": "No meetings are accessible with this account.",
        "Nenhuma reunião futura encontrada.": "No upcoming meetings found.",
        "Nenhuma reunião pendente": "No pending meetings",
        "Nenhuma tarefa ainda": "No tasks yet",
        "Nenhuma tarefa aqui": "No tasks here",
        "Nenhuma tarefa encontrada": "No tasks found",
        "Ninguém informado na ficha.": "No one specified on sheet.",
        "Nome": "Name",
        "Nome Completo": "Full Name",
        "Nome da equipe": "Team name",
        "Nome da pasta": "Folder name",
        "Nome de exibição": "Display name",
        "Nome do participante": "Participant name",
        "Nome na equipe": "Name in team",
        "Nome, e-mail ou login": "Name, email, or username",
        "Notas": "Notes",
        "Notas da Reunião": "Meeting Notes",
        "Notas da conversa": "Conversation notes",
        "Notas durante a gravação": "Notes during recording",
        "Notificações": "Notifications",
        "Notificações (%d)": "Notifications (%d)",
        "Nova Entrevista": "New Interview",
        "Nova Nota": "New Note",
        "Nova Tarefa": "New Task",
        "Nova conversa": "New conversation",
        "Nova equipe": "New team",
        "Nova nota": "New note",
        "Nova pasta": "New folder",
        "Nova tarefa": "New task",
        "Não consegui acessar esse arquivo. Se ele estiver no iPhone, desbloqueie o aparelho e tente importar de novo.": "Could not access this file. If it is on your iPhone, unlock it and try importing again.",
        "Não consegui acessar esse áudio. Se ele estiver no iPhone, desbloqueie o aparelho e tente importar de novo.": "Could not access this audio. If it is on your iPhone, unlock it and try importing again.",
        "Não encontramos uma equipe com esse código.": "No team was found with this code.",
        "Não encontrei a zona compartilhada desta equipe no iCloud. Entre novamente com o código da equipe.": "Could not find this team's shared zone in iCloud. Join again with the team code.",
        "Não foi possível abrir a biblioteca: %@": "Could not open library: %@",
        "Não foi possível abrir o áudio desta conversa": "Could not open this conversation's audio",
        "Não foi possível aceitar o convite do iCloud: %@": "Could not accept iCloud invite: %@",
        "Não foi possível adicionar a mídia": "Could not add media",
        "Não foi possível apagar %@: %@": "Could not delete %@: %@",
        "Não foi possível apagar definitivamente \"%@\": %@": "Could not permanently delete \"%@\": %@",
        "Não foi possível apagar definitivamente “%@”: %@": "Could not permanently delete “%@”: %@",
        "Não foi possível apagar o anexo: %@": "Could not delete attachment: %@",
        "Não foi possível apagar o arquivo definitivamente: %@": "Could not permanently delete the file: %@",
        "Não foi possível apagar o perfil: %@": "Could not delete profile: %@",
        "Não foi possível apagar “%@”: %@": "Could not delete “%@”: %@",
        "Não foi possível baixar as conversas da equipe: %@": "Could not download team conversations: %@",
        "Não foi possível concluir": "Could not complete",
        "Não foi possível concluir a operação": "Could not complete the operation",
        "Não foi possível continuar a paginação do espaço compartilhado.": "Could not continue loading the shared space.",
        "Não foi possível copiar o áudio da reunião: %@": "Could not copy meeting audio: %@",
        "Não foi possível criar a equipe no iCloud: %@": "Could not create team on iCloud: %@",
        "Não foi possível criar a pasta: %@": "Could not create folder: %@",
        "Não foi possível criar arquivo da reunião: %@": "Could not create the meeting file: %@",
        "Não foi possível devolver “%@” para a conversa. O arquivo pode ter sido movido ou apagado por fora do app.": "Could not restore “%@” to the conversation. The file may have been moved or deleted outside the app.",
        "Não foi possível duplicar: %@": "Could not duplicate: %@",
        "Não foi possível duplicar: %@. A cópia incompleta permaneceu no armazenamento para não apagar dados de forma insegura.": "Could not duplicate: %@. The incomplete copy was kept in storage to avoid deleting data unsafely.",
        "Não foi possível entrar": "Could not sign in",
        "Não foi possível entrar na equipe: %@": "Could not join team: %@",
        "Não foi possível excluir a conta": "Could not delete account",
        "Não foi possível exportar": "Could not export",
        "Não foi possível exportar: %@": "Could not export: %@",
        "Não foi possível guardar a foto do perfil: %@": "Could not save profile photo: %@",
        "Não foi possível guardar a pasta escolhida: %@": "Could not save the selected folder: %@",
        "Não foi possível guardar a sincronização pendente de %@: %@": "Could not save pending sync for %@: %@",
        "Não foi possível guardar esse arquivo: %@": "Could not save this file: %@",
        "Não foi possível guardar sua sessão: %@": "Could not save your session: %@",
        "Não foi possível importar a reunião: %@": "Could not import meeting: %@",
        "Não foi possível ler ou salvar a fila do iCloud: %@": "Could not read or save iCloud queue: %@",
        "Não foi possível mover o arquivo para a lixeira: %@": "Could not move file to trash: %@",
        "Não foi possível mover o áudio da gravação para a lixeira: %@": "Could not move the recording audio to Trash: %@",
        "Não foi possível obter token de acesso.": "Could not get an access token.",
        "Não foi possível preparar o convite desta equipe.": "Could not prepare this team's invitation.",
        "Não foi possível recuperar o arquivo: %@": "Could not recover file: %@",
        "Não foi possível registrar o Ōmu no servidor do Granola.": "Could not register Ōmu with the Granola server.",
        "Não foi possível remover \"%@\": %@": "Could not remove \"%@\": %@",
        "Não foi possível remover esse arquivo: %@": "Could not remove this file: %@",
        "Não foi possível renomear: %@": "Could not rename: %@",
        "Não foi possível restaurar \"%@\".": "Could not restore \"%@\".",
        "Não foi possível restaurar %@.": "Could not restore %@.",
        "Não foi possível salvar": "Could not save",
        "Não foi possível salvar a diarização: %@": "Could not save diarization: %@",
        "Não foi possível salvar a transcrição: %@": "Could not save transcription: %@",
        "Não foi possível salvar as informações: %@": "Could not save details: %@",
        "Não foi possível salvar as notas: %@": "Could not save notes: %@",
        "Não foi possível salvar: %@": "Could not save: %@",
        "Não foi possível validar a credencial da Apple.": "Could not validate Apple credential.",
        "Não informado": "Not specified",
        "Não iniciado": "To Do",
        "O Google Calendar respondeu algo inesperado.": "Google Calendar responded unexpectedly.",
        "O Granola respondeu algo que o Ōmu não reconheceu.": "Granola returned something Ōmu did not recognize.",
        "O Granola respondeu de forma inesperada.": "Granola responded unexpectedly.",
        "O Granola respondeu: %@.": "Granola responded: %@.",
        "O anexo foi movido para a lixeira, mas a lista da conversa não pôde ser atualizada. Ele continua na lixeira para não ser perdido.": "The attachment was moved to Trash, but the conversation list could not be updated. It remains in Trash so it is not lost.",
        "O anexo não está dentro da pasta de gravações e não foi alterado.": "The attachment is not inside the recordings folder and was not changed.",
        "O arquivo de áudio escolhido não foi encontrado.": "The selected audio file was not found.",
        "O arquivo sai do seu Mac e não poderá ser recuperado.": "The file will be removed from your Mac and cannot be recovered.",
        "O compartilhamento desta equipe não é válido.": "This team's share is invalid.",
        "O convite não contém uma equipe válida do Ōmu.": "This invitation does not contain a valid Ōmu team.",
        "O código e o link atuais deixarão de funcionar. Por segurança, os participantes aceitos precisarão entrar novamente com o novo código.": "The current code and link will stop working. For security, approved participants must join again with the new code.",
        "O download continua de onde parou se a conexão cair.": "The download resumes where it left off if your connection drops.",
        "O navegador não abriu — confira se o Ōmu pode abrir janelas e tente de novo.": "The browser did not open — make sure Ōmu can open windows and try again.",
        "O navegador voltou sem o código de autorização. Tente de novo.": "The browser returned without an authorization code. Try again.",
        "O proprietário da equipe não pode ser removido.": "The team owner cannot be removed.",
        "O que aconteceu aqui? Use #etiqueta para agrupar": "What happened here? Use #tags to group notes",
        "O que cabe nesta aba": "What belongs in this tab",
        "O reconhecimento de fala não está disponível agora.": "Speech recognition is not available right now.",
        "O resumo aparecerá depois do processamento.": "Summary will appear after processing.",
        "O retorno de autorização não corresponde à conexão iniciada. Tente conectar novamente.": "The authorization return does not match the connection that was started. Connect again.",
        "O servidor de autorização respondeu de forma inesperada.": "The authorization server responded unexpectedly.",
        "O servidor do Google respondeu de forma inesperada.": "The Google server responded unexpectedly.",
        "O servidor respondeu: %@.": "The server responded: %@.",
        "O áudio capturado até agora é descartado.": "The recorded audio so far will be discarded.",
        "O áudio da gravação só pode ser removido depois que a transcrição terminar.": "Recording audio can be removed only after transcription finishes.",
        "OK": "OK",
        "Ocorrência anterior (Shift+Enter)": "Previous occurrence (Shift+Enter)",
        "Ocultar": "Hide",
        "Ocultar coluna %@": "Hide %@ column",
        "Ocultar seção %@": "Hide %@ section",
        "Ocultar tarefa": "Hide task",
        "Ocultas": "Hidden",
        "Ocupado": "Busy",
        "Offline": "Offline",
        "Online": "Online",
        "Ontem": "Yesterday",
        "Opções": "Options",
        "Opções da conversa": "Conversation options",
        "Opções de compartilhamento": "Sharing options",
        "Ordenação": "Sort",
        "Organizar": "Organize",
        "Ou digite nome, e-mail ou login": "Or type name, email, or username",
        "Ouvindo…": "Listening…",
        "Ouvir a partir de %@": "Listen from %@",
        "Ouvir a partir desta palavra": "Listen from this word",
        "Ouvir áudio": "Listen to audio",
        "PASTA": "FOLDER",
        "PDF colado": "Pasted PDF",
        "Painel": "Panel",
        "Painel de Mídias": "Media Board",
        "Painel de Tarefas": "Tasks Board",
        "Papel": "Role",
        "Para salvar nomes da equipe, publique o campo “nomesDosParticipantes” (Bytes) no tipo Equipe do CloudKit Dashboard. O nome atual continua preservado neste Mac.": "To save team names, deploy the “nomesDosParticipantes” (Bytes) field on the Equipe type in CloudKit Dashboard. The current name remains saved on this Mac.",
        "Parar e transcrever": "Stop and transcribe",
        "Participante aceito": "Participant accepted",
        "Participantes": "Participants",
        "Participantes não informados": "Participants not specified",
        "Pasta": "Folder",
        "Pasta ativa: %@": "Active folder: %@",
        "Pasta destino": "Destination folder",
        "Pastas": "Folders",
        "Pastas da Biblioteca": "Library Folders",
        "Pastas da biblioteca": "Library folders",
        "Pausa": "Pause",
        "Pausado": "Paused",
        "Pausar": "Pause",
        "Pausar gravação": "Pause recording",
        "Pausar transcrições e resumos automáticos": "Pause automatic transcripts and summaries",
        "Perfil": "Profile",
        "Perfil pessoal": "Personal profile",
        "Permissão": "Permission",
        "Permissão de %@": "%@ permission",
        "Permissões": "Permissions",
        "Personalizar": "Customize",
        "Personalizar cartões": "Customize cards",
        "Personalização": "Customization",
        "Pesquisa": "Research",
        "Pesquisar na transcrição: Cmd + F": "Search transcript: Cmd + F",
        "Pessoal": "Personal",
        "Peça o código ao administrador da equipe.": "Ask the team admin for the code.",
        "Player": "Player",
        "Pode fechar esta janela e voltar ao Ōmu.": "You can close this window and return to Ōmu.",
        "Por data": "By date",
        "Por nome": "By name",
        "Por prioridade": "By priority",
        "Por status": "By status",
        "Português (Brasil)": "Portuguese (Brazil)",
        "Posição do áudio": "Audio position",
        "Prazo perto": "Due soon",
        "Preencher": "Fill",
        "Preferências": "Preferences",
        "Preparando a biblioteca. Gravar e importar estarão disponíveis em instantes.": "Preparing the library. Recording and importing will be available shortly.",
        "Preparando biblioteca": "Preparing library",
        "Preparando áudio": "Preparing audio",
        "Presencial": "In-person",
        "Primeira rodada de testes do fluxo de cadastro.": "First round of onboarding flow tests.",
        "Prioridade": "Priority",
        "Prioridade:": "Priority:",
        "Processamento": "Processing",
        "Processamento automático": "Automatic processing",
        "Processando": "Processing",
        "Processando conversa": "Processing conversation",
        "Pronto": "Ready",
        "Pronto para transcrever": "Ready to transcribe",
        "Proprietário": "Owner",
        "Prévia": "Preview",
        "Próxima ocorrência (Enter)": "Next occurrence (Enter)",
        "Próximas 24h": "Next 24 hours",
        "Próximos 7 dias": "Next 7 days",
        "Quando ativado, novos áudios não entram na fila até você selecionar Transcrever.": "When enabled, new audio stays queued until you select Transcribe.",
        "Quando desligado, a ficha não abre automaticamente ao fim do processamento — ideal quando a ficha já foi preenchida pelo calendário.": "When disabled, details sheet will not pop up after processing.",
        "Quando desligado, as palavras continuam destacadas por cor, mas o percentual não aparece.": "When disabled, word confidence colors remain but numbers are hidden.",
        "Quando ligado, transcrições e resumos em outro idioma são traduzidos localmente para português ou inglês. Quando desligado, o idioma falado é preservado.": "When enabled, transcripts and summaries in another language are translated locally into Portuguese or English. When disabled, the spoken language is preserved.",
        "Quando uma conversa tiver próximos passos ou tarefas criadas, elas ficarão reunidas nesta página.": "When conversations have next steps or tasks, they will appear here.",
        "Quem é quem?": "Who’s who?",
        "Qwen": "Qwen",
        "Reativar som": "Unmute",
        "Recebimento de arquivos": "File receiving",
        "Recentes": "Recent",
        "Recolher": "Collapse",
        "Reconfigurar acesso por código": "Reconfigure code access",
        "Reconhecimento": "Recognition",
        "Reconhecimento de fala": "Speech recognition",
        "Recortar": "Trim",
        "Refinando com o modelo local…": "Refining with local model…",
        "Registrado": "Registered",
        "Regras": "Rules",
        "Regras de Prazo": "Due Date Rules",
        "Remove deste Mac o perfil e seus dados pessoais, sem apagar os espaços de equipe nem as preferências do app.": "Removes this profile and its personal data from this Mac without deleting team spaces or app preferences.",
        "Remover": "Remove",
        "Remover %@?": "Remove %@?",
        "Remover acesso": "Remove access",
        "Remover anexo": "Remove attachment",
        "Remover da equipe": "Remove from team",
        "Remover da lista": "Remove from list",
        "Remover da pasta": "Remove from folder",
        "Remover pessoa": "Remove person",
        "Removido": "Removed",
        "Renomear": "Rename",
        "Renomear falante": "Rename speaker",
        "Renomear pasta": "Rename folder",
        "Repetir": "Repeat",
        "Reprocessa a conversa inteira: transcrição, resumo e próximos passos": "Reprocesses the entire conversation: transcription, summary, and next steps",
        "Reprocessar": "Reprocess",
        "Reproduzindo": "Playing",
        "Reproduzir": "Play",
        "Responsável": "Assignee",
        "Restaurar": "Restore",
        "Restaurar %@": "Restore %@",
        "Restaurar Tudo": "Restore All",
        "Restaurar a pasta %@": "Restore %@ folder",
        "Restaurar arquivo": "Restore file",
        "Restaurar padrão": "Restore default",
        "Restaurar pasta": "Restore folder",
        "Restaurar tamanho": "Restore size",
        "Restaurar tarefa": "Restore task",
        "Restaurar todos os arquivos da lixeira": "Restore all files from Trash",
        "Restaure a pasta inteira, com a cor e a imagem que tinha, ou traga de volta só uma conversa.": "Restore the entire folder with its original color and image, or bring back just one conversation.",
        "Resumo": "Summary",
        "Resumo da Reunião": "Meeting Summary",
        "Resumo da conversa": "Conversation summary",
        "Resumo indisponível": "Summary unavailable",
        "Retomar": "Resume",
        "Retomar gravação": "Resume recording",
        "Retomar transcrição": "Resume transcription",
        "Reunião": "Meeting",
        "Reunião sem título": "Untitled meeting",
        "Reuniões": "Meetings",
        "Reuniões acessíveis": "Accessible meetings",
        "Reuniões do Calendário": "Calendar Meetings",
        "Reuniões futuras (próximas 24 horas)": "Upcoming meetings (next 24 hours)",
        "Reuniões pendentes": "Pending meetings",
        "Reuniões pendentes ignoradas": "Ignored pending meetings",
        "Rótulo": "Label",
        "SEM RESPONSÁVEL": "NO ASSIGNEE",
        "Sair": "Sign Out",
        "Salta o áudio para o instante desta palavra.": "Jumps audio to this word's timestamp.",
        "Salvando...": "Saving...",
        "Salvando…": "Saving…",
        "Salvar": "Save",
        "Salvar alterações": "Save changes",
        "Salvar aqui": "Save here",
        "Salvar como…": "Save as…",
        "Salvar configurações": "Save settings",
        "Salvar informações": "Save details",
        "Salvo": "Saved",
        "Salvo no Mac": "Saved to Mac",
        "Segurança": "Security",
        "Segurança do Perfil": "Profile Security",
        "Selecionar": "Select",
        "Selecionar equipe": "Select team",
        "Selecione uma pasta": "Select a folder",
        "Sem conexão com o Granola: %@.": "No connection to Granola: %@.",
        "Sem cor": "No color",
        "Sem data": "No date",
        "Sem deadline": "No deadline",
        "Sem descrição": "No description",
        "Sem responsável": "No assignee",
        "Sem título": "Untitled",
        "Senha": "Password",
        "Sessão": "Session",
        "Seu nome": "Your name",
        "Seção recolhida — pode soltar aqui.": "Section collapsed — drop here.",
        "Sign in with Apple": "Sign in with Apple",
        "Silenciar": "Mute",
        "Sincronizado com o iCloud": "Synced with iCloud",
        "Sincronizando com o iCloud…": "Syncing with iCloud…",
        "Sistema": "System",
        "Sobre": "About",
        "Sobre Configurações": "About Settings",
        "Sobre a biblioteca": "About library",
        "Sobre a gravação": "About recording",
        "Sobre a página de mídias": "About the Media page",
        "Sobre esta tela": "About this screen",
        "Sobre nomear vozes": "About naming speakers",
        "Sobre o aplicativo": "About application",
        "Sobre o painel de tarefas": "About the tasks board",
        "Soltar para adicionar": "Drop to add",
        "Solte uma tarefa aqui para mudar para %@.": "Drop a task here to change to %@.",
        "Solte uma tarefa aqui.": "Drop a task here.",
        "Somado a partir dos nomes de Equipe e Externos.": "Combined from Team and External names.",
        "Somente a conta que criou a equipe pode consultar participantes, alterar configurações, trocar o código ou excluir a equipe.": "Only the account that created the team can view participants, change settings, change the code, or delete the team.",
        "Somente administradores": "Admins only",
        "Somente leitura": "Read-only",
        "Somente quem criou a equipe pode alterar estas configurações.": "Only the person who created the team can change these settings.",
        "Status": "Status",
        "Substituir arquivo": "Replace file",
        "Sugestões": "Suggestions",
        "Sugestões da conversa": "Conversation suggestions",
        "TAREFA": "TASK",
        "TRANSCRIÇÃO": "TRANSCRIPTION",
        "Tabela": "Table",
        "Tamanho": "Size",
        "Tamanho do arquivo": "File size",
        "Tarefa": "Task",
        "Tarefa removida de %@. Restaure para voltar ao painel de tarefas dessa conversa.": "Task removed from %@. Restore it to return it to this conversation's task board.",
        "Tarefas": "Tasks",
        "Tarefas da Conversa": "Conversation Tasks",
        "Tarefas pendentes": "Pending tasks",
        "Temas": "Topics",
        "Tempo": "Time",
        "Tempo atual da gravação": "Current recording time",
        "Tempo de gravação": "Recording time",
        "Tempo decorrido": "Elapsed time",
        "Tempo esgotado esperando sua autorização — volte ao navegador e tente de novo.": "Timed out waiting for authorization — return to the browser and try again.",
        "Tentar agora": "Try now",
        "Tentar novamente": "Try again",
        "Tente buscar por outro título na lixeira.": "Try searching Trash with a different title.",
        "Tente buscar por outro título ou estado de processamento.": "Try searching with a different title or processing status.",
        "Tente limpar a seleção ou buscar por outra conversa.": "Try clearing selection or searching for another conversation.",
        "Tente limpar a seleção, trocar o tipo de arquivo ou buscar por outra conversa.": "Try clearing selection, switching file type, or searching for another conversation.",
        "Tipo": "Type",
        "Tipo de arquivo": "File type",
        "Todas": "All",
        "Todas as conversas": "All conversations",
        "Todas as mídias": "All media",
        "Todas as tarefas": "All tasks",
        "Todo": "All",
        "Todos": "All",
        "Todos os arquivos": "All files",
        "Todos os membros": "All members",
        "Todos os status": "All statuses",
        "Todos os tipos": "All types",
        "Traduzir automaticamente para o idioma do sistema": "Automatically translate to the system language",
        "Transcrevendo…": "Transcribing…",
        "Transcrever": "Transcribe",
        "Transcrito": "Transcribed",
        "Transcrição": "Transcription",
        "Transcrição concluída": "Transcription complete",
        "Transcrição em preparação": "Preparing transcription",
        "Transcrição falhou": "Transcription failed",
        "Transcrição finalizada sem falas": "Transcription finished with no speech",
        "Trocar código de entrada": "Change join code",
        "Trocar código e revogar acessos": "Change code and revoke access",
        "Trocar foto do perfil": "Change profile photo",
        "Trocar o código cria um novo compartilhamento e exige que os participantes entrem novamente. Excluir a equipe apaga a zona compartilhada e os dados locais deste Mac.": "Changing the code creates a new share and requires participants to join again. Deleting the team removes the shared zone and this Mac's local data.",
        "Trocar o código de entrada?": "Change the join code?",
        "Trocar…": "Change…",
        "Troque o filtro para ver as outras notas.": "Change filter to view other notes.",
        "Truncar": "Truncate",
        "Tudo": "All",
        "Título": "Title",
        "Título da conversa": "Conversation title",
        "Título da entrevista": "Interview title",
        "Um anexo não pôde ser apagado e continua na lixeira.": "One attachment could not be deleted and remains in Trash.",
        "Um ou mais anexos não puderam ser restaurados. Revise os itens restantes na lixeira.": "One or more attachments could not be restored. Review the remaining items in Trash.",
        "Uma janela pequena, sempre visível por cima dos outros apps, para anotar, pausar e finalizar sem voltar ao Ōmu.": "A compact floating window to take notes, pause, and finish without switching back to Ōmu.",
        "Uma operação pendente do iCloud não contém a conversa esperada.": "A pending iCloud operation does not contain the expected conversation.",
        "Upload": "Upload",
        "Usar": "Use",
        "Usar foto": "Use photo",
        "Usar imagem": "Use image",
        "Usar pasta do app": "Use app folder",
        "Use Mover para pasta no menu de um card para organizar conversas aqui.": "Use Move to folder from a card's menu to organize conversations here.",
        "Use esta ação uma vez para que o código também libere a zona compartilhada no iCloud. Convites pendentes por e-mail deixam de valer.": "Use this once to release the shared iCloud zone.",
        "Use o botão de adicionar para criar uma tarefa nesta conversa.": "Use the add button to create a task in this conversation.",
        "Velocidade": "Speed",
        "Vem da duração do áudio desta conversa.": "Based on this conversation's audio duration.",
        "Vence amanhã": "Due tomorrow",
        "Vence hoje": "Due today",
        "Ver a conversa": "View conversation",
        "Ver quem participou": "View participants",
        "Vincular": "Link",
        "Vincular conta": "Link account",
        "Visibilidade dos arquivos": "File visibility",
        "Visualizar": "Preview",
        "Visualização": "View",
        "Você ainda não faz parte de nenhuma equipe.": "You are not part of a team yet.",
        "Você ainda não tem equipes. Use o + para criar a primeira ou entre com um código.": "You do not have any teams yet. Use + to create your first or join one with a code.",
        "Você precisa desbloquear seu iPhone antes de importar esse arquivo.": "Unlock your iPhone before importing this file.",
        "Você precisa desbloquear seu iPhone antes de importar esse áudio.": "Unlock your iPhone before importing this audio.",
        "Você será avisado quando a transcrição terminar.": "You will be notified when transcription finishes.",
        "Você só pode alterar o próprio nome nesta equipe.": "You can only change your own name in this team.",
        "Você também pode apontar uma pasta que já tenha os modelos GGUF.": "You can also choose a folder that already contains the GGUF models.",
        "Voltar": "Back",
        "Voltar 10 segundos": "Back 10 seconds",
        "Voltar para a biblioteca": "Back to library",
        "Voltar para a gravação": "Back to recording",
        "Voltar para a gravação em andamento": "Return to recording in progress",
        "Voltar para a lista": "Back to list",
        "Voltar para todas as pastas": "Back to all folders",
        "Volte ao Ōmu e tente novamente.": "Return to Ōmu and try again.",
        "Volume": "Volume",
        "Voz": "Voice",
        "Vídeo colado": "Pasted video",
        "Waveform": "Waveform",
        "Whisper": "Whisper",
        "Workspace": "Workspace",
        "anexo": "attachment",
        "cerca de %.1f h": "about %.1f hr",
        "cerca de %d min": "about %d min",
        "conversas selecionadas": "selected conversations",
        "dd/mm/aaaa": "mm/dd/yyyy",
        "descrição da imagem": "image description",
        "distinguindo falantes…": "distinguishing speakers…",
        "em breve": "soon",
        "este participante": "this participant",
        "expirada": "expired",
        "item da conversa": "conversation item",
        "link": "link",
        "menos de 1 min": "under 1 min",
        "na fila (posição %d)": "in queue (position %d)",
        "notas": "notes",
        "não foi possível abrir a pasta de suporte do app": "could not open the app support folder",
        "obrigatório": "required",
        "observação": "note",
        "ocultas": "hidden",
        "participantes ainda não carregados": "participants not loaded yet",
        "pendente": "pending",
        "pronto para transcrever": "ready to transcribe",
        "resolvendo falantes pelo contexto…": "resolving speakers from context…",
        "resumindo…": "summarizing…",
        "salvando…": "saving…",
        "texto em destaque": "highlighted text",
        "traduzindo…": "translating…",
        "transcrevendo…": "transcribing…",
        "transcrito": "transcribed",
        "transcrito e resumido": "transcribed and summarized",
        "ÁUDIO": "AUDIO",
        "Áudio colado": "Pasted audio",
        "Áudio da gravação de %@. A transcrição e o resumo continuam na conversa; restaure para poder ouvir de novo.": "Recording audio from %@. The transcript and summary remain in the conversation; restore it to listen again.",
        "Áudio do sistema": "System audio",
        "É o nome exibido no cartão acima.": "This is the name displayed on the card above.",
    ]
}
