# -*- coding: utf-8 -*-
import json
import os
import sys
from pathlib import Path

# Funciona tanto como módulo (`python3 -m Scripts.build_complete_catalog`) quanto
# como script direto, que é a forma mostrada nos comandos de manutenção.
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from Scripts.generate_translations import TRANSLATIONS, generate_xcstrings

# Mapeamento completo e preciso para todas as chaves pendentes
EXTRA_TRANSLATIONS = {
    # Strings that were discovered by extraction after the initial glossary.
    # Keep this list in the source generator (rather than hand-editing the
    # catalog) so regenerating the catalog never reintroduces Portuguese into
    # the English localization.
    "Autorização concluída": "Authorization complete",
    "Autorização recusada": "Authorization declined",
    "Escolha uma foto para %@": "Choose a photo for %@",
    "Meu perfil": "My profile",
    "Membro da equipe": "Team member",
    "O anexo não está dentro da pasta de gravações e não foi alterado.": "The attachment is not inside the recordings folder and was not changed.",
    "O anexo foi movido para a lixeira, mas a lista da conversa não pôde ser atualizada. Ele continua na lixeira para não ser perdido.": "The attachment was moved to Trash, but the conversation list could not be updated. It remains in Trash so it is not lost.",
    "Pode fechar esta janela e voltar ao Ōmu.": "You can close this window and return to Ōmu.",
    "Um anexo não pôde ser apagado e continua na lixeira.": "One attachment could not be deleted and remains in Trash.",
    "%d anexos não puderam ser apagados e continuam na lixeira.": "%d attachments could not be deleted and remain in Trash.",
    "Usar foto": "Use photo",
    "Volte ao Ōmu e tente novamente.": "Return to Ōmu and try again.",
    "A lixeira está vazia": "Trash is empty",
    "A pasta %@ está vazia": "%@ is empty",
    "A pasta ficará disponível para organizar conversas.": "The folder will be available to organize conversations.",
    "A primeira conversa aparecerá aqui depois de gravar ou importar um áudio.": "Your first conversation will appear here after you record or import audio.",
    "A reunião %@ não foi encontrada no Google Calendar.": "Meeting %@ was not found in Google Calendar.",
    "A reunião %@ não foi encontrada no Granola.": "Meeting %@ was not found in Granola.",
    "A reunião %@ tem uma data inválida no Google Calendar.": "Meeting %@ has an invalid date in Google Calendar.",
    "ACESSO": "ACCESS",
    "Aguardar revisão": "Wait for review",
    "Ana Silva": "Jane Doe",
    "Arquivos movidos da biblioteca aparecerão aqui e poderão ser recuperados.": "Files moved from the library appear here and can be recovered.",
    "Ativo": "Active",
    "AÇÕES": "ACTIONS",
    "Convite pendente": "Invitation pending",
    "Entrar automaticamente": "Join automatically",
    "Escolha fotos, vídeos, áudios, PDFs ou outros arquivos para salvar nesta conversa.": "Choose photos, videos, audio, PDFs, or other files to save in this conversation.",
    "Essa ação remove o áudio, a transcrição e o resumo do Mac e não pode ser desfeita.": "This removes the audio, transcript, and summary from your Mac and cannot be undone.",
    "Essa ação remove permanentemente todos os arquivos da lixeira e não pode ser desfeita.": "This permanently removes every file from Trash and cannot be undone.",
    "Esvaziar lixeira?": "Empty Trash?",
    "Evento sem título": "Untitled event",
    "Favorite uma conversa pelo botão de estrela para ela aparecer aqui.": "Favorite a conversation with the star button to show it here.",
    "IDENTIDADE": "IDENTITY",
    "João Santos": "John Smith",
    "Leitura e escrita": "Read and write",
    "MEMBRO": "MEMBER",
    "Nenhum arquivo encontrado": "No files found",
    "Nenhum favorito ainda": "No favorites yet",
    "Não consegui acessar esse arquivo. Se ele estiver no iPhone, desbloqueie o aparelho e tente importar de novo.": "Could not access this file. If it is on your iPhone, unlock it and try importing again.",
    "Não foi possível apagar definitivamente \"%@\": %@": "Could not permanently delete \"%@\": %@",
    "Não foi possível apagar “%@”: %@": "Could not delete “%@”: %@",
    "Não foi possível concluir": "Could not complete",
    "Não foi possível concluir a operação": "Could not complete the operation",
    "Não foi possível devolver “%@” para a conversa. O arquivo pode ter sido movido ou apagado por fora do app.": "Could not restore “%@” to the conversation. The file may have been moved or deleted outside the app.",
    "Não foi possível exportar": "Could not export",
    "Não foi possível obter token de acesso.": "Could not get an access token.",
    "Não foi possível remover \"%@\": %@": "Could not remove \"%@\": %@",
    "Não foi possível restaurar \"%@\".": "Could not restore \"%@\".",
    "O Google Calendar respondeu algo inesperado.": "Google Calendar responded unexpectedly.",
    "O Granola respondeu algo que o Ōmu não reconheceu.": "Granola returned something Ōmu did not recognize.",
    "Ocupado": "Busy",
    "Offline": "Offline",
    "Proprietário": "Owner",
    "Reuniões pendentes ignoradas": "Ignored pending meetings",
    "Somente administradores": "Admins only",
    "Somente leitura": "Read-only",
    "Tempo esgotado esperando sua autorização — volte ao navegador e tente de novo.": "Timed out waiting for authorization — return to the browser and try again.",
    "Tente buscar por outro título na lixeira.": "Try searching Trash with a different title.",
    "Tente buscar por outro título ou estado de processamento.": "Try searching with a different title or processing status.",
    "Um ou mais anexos não puderam ser restaurados. Revise os itens restantes na lixeira.": "One or more attachments could not be restored. Review the remaining items in Trash.",
    "Use Mover para pasta no menu de um card para organizar conversas aqui.": "Use Move to folder from a card's menu to organize conversations here.",
    "anexo": "attachment",
    "descrição da imagem": "image description",
    "item da conversa": "conversation item",
    "link": "link",
    "na fila (posição %d)": "in queue (position %d)",
    "observação": "note",
    "pronto para transcrever": "ready to transcribe",
    "texto em destaque": "highlighted text",
    "transcrito": "transcribed",
    "transcrito e resumido": "transcribed and summarized",
    "A sessão expirou e não há refresh token. Conecte de novo.": "The session expired and no refresh token is available. Connect again.",
    "A sessão expirou e o Ōmu não tem como renová-la. Conecte de novo.": "The session expired and Ōmu cannot renew it. Connect again.",
    "A versão instalada ainda tenta consultar o tipo de registro “Conversa”, mas ele não está indexado no CloudKit. Atualize o Ōmu para a versão que sincroniza diretamente a zona compartilhada; suas alterações locais permanecem neste Mac.": "This version still tries to query the “Conversa” record type, but it is not indexed in CloudKit. Update Ōmu to the version that syncs the shared zone directly; your local changes remain on this Mac.",
    "A zona compartilhada desta equipe ainda não está disponível nesta Apple Account. Peça ao proprietário para confirmar o compartilhamento e entre novamente com o código da equipe.": "This team's shared zone is not yet available to this Apple Account. Ask the owner to confirm sharing, then join again with the team code.",
    "A exclusão ainda não pode ser concluída porque o tipo público “EquipeExcluida” não está publicado no CloudKit de produção. No CloudKit Dashboard, publique esse tipo e os campos equipeID, excluidaEm e estadoDaExclusao; nenhum dado foi apagado.": "Deletion cannot be completed because the public “EquipeExcluida” type is not deployed to the production CloudKit schema. In CloudKit Dashboard, deploy that type and the equipeID, excluidaEm, and estadoDaExclusao fields; no data was deleted.",
    "A equipe foi aceita, mas o tipo de registro “Conversa” ainda não está publicado no CloudKit de produção. Peça ao proprietário da equipe para publicar o esquema no CloudKit Dashboard; suas alterações continuam neste Mac até isso acontecer.": "The team was accepted, but the “Conversa” record type is not yet deployed to the production CloudKit schema. Ask the team owner to deploy the schema in CloudKit Dashboard; your changes remain on this Mac until then.",
    "A permissão do proprietário da equipe não pode ser alterada.": "The team owner's permission cannot be changed.",
    "Autorização cancelada ou recusada no navegador.": "Authorization was canceled or declined in the browser.",
    "Client ID do Google não configurado. Configure-o no arquivo local do projeto.": "Google Client ID is not configured. Set it in the project's local configuration file.",
    "Esse membro não faz mais parte do compartilhamento.": "This member is no longer part of the share.",
    "Esta equipe ainda não foi publicada no CloudKit.": "This team has not been published to CloudKit yet.",
    "Entre no iCloud neste Mac para usar equipes compartilhadas.": "Sign in to iCloud on this Mac to use shared teams.",
    "Falha ao iniciar servidor local para OAuth: %@": "Could not start the local OAuth server: %@",
    "Falta um modelo na pasta escolhida. Complete a pasta ou volte a usar a pasta do app para baixar.": "A model is missing from the selected folder. Complete the folder or switch back to the app folder to download it.",
    "Informe um nome para mostrar na equipe.": "Enter a name to display in the team.",
    "Não encontrei a zona compartilhada desta equipe no iCloud. Entre novamente com o código da equipe.": "Could not find this team's shared zone in iCloud. Join again with the team code.",
    "Não encontramos uma equipe com esse código.": "No team was found with this code.",
    "Não foi possível apagar %@: %@": "Could not delete %@: %@",
    "Não foi possível continuar a paginação do espaço compartilhado.": "Could not continue loading the shared space.",
    "Não foi possível guardar a pasta escolhida: %@": "Could not save the selected folder: %@",
    "Não foi possível guardar esse arquivo: %@": "Could not save this file: %@",
    "Não foi possível mover o áudio da gravação para a lixeira: %@": "Could not move the recording audio to Trash: %@",
    "Não foi possível preparar o convite desta equipe.": "Could not prepare this team's invitation.",
    "Não foi possível registrar o Ōmu no servidor do Granola.": "Could not register Ōmu with the Granola server.",
    "Não foi possível remover esse arquivo: %@": "Could not remove this file: %@",
    "Não foi possível salvar": "Could not save",
    "Não foi possível restaurar %@.": "Could not restore %@.",
    "O Granola respondeu de forma inesperada.": "Granola responded unexpectedly.",
    "O Granola respondeu: %@.": "Granola responded: %@.",
    "O áudio da gravação só pode ser removido depois que a transcrição terminar.": "Recording audio can be removed only after transcription finishes.",
    "O convite não contém uma equipe válida do Ōmu.": "This invitation does not contain a valid Ōmu team.",
    "O navegador não abriu — confira se o Ōmu pode abrir janelas e tente de novo.": "The browser did not open — make sure Ōmu can open windows and try again.",
    "O navegador voltou sem o código de autorização. Tente de novo.": "The browser returned without an authorization code. Try again.",
    "O retorno de autorização não corresponde à conexão iniciada. Tente conectar novamente.": "The authorization return does not match the connection that was started. Connect again.",
    "O servidor de autorização respondeu de forma inesperada.": "The authorization server responded unexpectedly.",
    "O servidor do Google respondeu de forma inesperada.": "The Google server responded unexpectedly.",
    "O servidor respondeu: %@.": "The server responded: %@.",
    "O compartilhamento desta equipe não é válido.": "This team's share is invalid.",
    "O proprietário da equipe não pode ser removido.": "The team owner cannot be removed.",
    "Para salvar nomes da equipe, publique o campo “nomesDosParticipantes” (Bytes) no tipo Equipe do CloudKit Dashboard. O nome atual continua preservado neste Mac.": "To save team names, deploy the “nomesDosParticipantes” (Bytes) field on the Equipe type in CloudKit Dashboard. The current name remains saved on this Mac.",
    "Sem conexão com o Granola: %@.": "No connection to Granola: %@.",
    "Somente quem criou a equipe pode alterar estas configurações.": "Only the person who created the team can change these settings.",
    "Uma operação pendente do iCloud não contém a conversa esperada.": "A pending iCloud operation does not contain the expected conversation.",
    "Você precisa desbloquear seu iPhone antes de importar esse arquivo.": "Unlock your iPhone before importing this file.",
    "Você só pode alterar o próprio nome nesta equipe.": "You can only change your own name in this team.",
    "participantes ainda não carregados": "participants not loaded yet",
    "ÁUDIO": "AUDIO",
    "Áudio colado": "Pasted audio",
    "Áudio da gravação de %@. A transcrição e o resumo continuam na conversa; restaure para poder ouvir de novo.": "Recording audio from %@. The transcript and summary remain in the conversation; restore it to listen again.",
    "Áudio do sistema": "System audio",
    "cerca de %.1f h": "about %.1f hr",
    "cerca de %d min": "about %d min",
    "Código de entrada": "Join code",
    "Código indisponível para equipes criadas antes desta atualização.": "Codes are unavailable for teams created before this update.",
    "Compartilhar conversa": "Share conversation",
    "Compartilhe este código com quem deve entrar. Ao informá-lo no Ōmu, a pessoa recebe acesso de leitura e escrita à equipe nesta Apple Account.": "Share this code with people who need to join. Entering it in Ōmu gives them read and write access to this team with their Apple Account.",
    "Compartilhe o código para dar acesso ao espaço compartilhado.": "Share the code to grant access to the shared space.",
    "Concluído": "Completed",
    "Conectado, o Ōmu pode ver suas reuniões do Granola e importá-las para a biblioteca — notas e resumo sempre; a transcrição quando o seu plano incluir. Nada é enviado para fora do seu Mac além do fluxo de autorização e das chamadas ao próprio Granola.": "Once connected, Ōmu can view your Granola meetings and import them into the library — always with notes and a summary, and with a transcript when your plan includes it. Nothing leaves your Mac except the authorization flow and calls to Granola.",
    "Confiança %.0f%% — baixa": "Confidence %.0f%% — low",
    "Conta proprietária": "Owner account",
    "Conversa %@. %@": "Conversation %@. %@",
    "Conversa movida para a lixeira. Restaure para acessar transcrição, notas e mídia.": "Conversation moved to Trash. Restore it to access the transcript, notes, and media.",
    "Conversa salva só neste Mac": "Conversation saved on this Mac only",
    "Copiar conversa inteira": "Copy entire conversation",
    "Cor e imagem": "Color and image",
    "Corrigir o texto desta fala": "Correct this speaker's text",
    "Corrigir o texto deste trecho": "Correct this passage",
    "Criar e mover": "Create and move",
    "Criar nova pasta…": "Create new folder…",
    "Criar pasta e mover": "Create folder and move",
    "Crie uma equipe ou entre com um código no seu perfil.": "Create a team or join one with a code in your profile.",
    "Crie uma equipe para vincular ao seu perfil.": "Create a team to link to your profile.",
    "Crie uma pasta nova e esta conversa será movida para ela.": "Create a new folder and this conversation will be moved into it.",
    "Data da entrevista": "Interview date",
    "Data não reconhecida. Use %@.": "Unrecognized date. Use %@.",
    "Datas da conversa": "Conversation dates",
    "Deadline perto: a tarefa será marcada como prioridade alta.": "Due soon: this task will be marked high priority.",
    "Defina título, responsável, prioridade e deadline antes de salvar.": "Set a title, assignee, priority, and due date before saving.",
    "Desfavoritar": "Remove from Favorites",
    "Editar nome": "Edit name",
    "Editar título e descrição": "Edit title and description",
    "Editar…": "Edit…",
    "Ela vai para a lixeira, de onde dá para restaurar depois.": "It moves to Trash, where you can restore it later.",
    "em breve": "soon",
    "Email Primário": "Primary email",
    "Entrar": "Sign in",
    "Entrar com código": "Join with code",
    "Entrar em uma equipe": "Join a team",
    "Entrevista com Ana Silva": "Interview with Jane Doe",
    "Escolha uma imagem para a pasta": "Choose an image for the folder",
    "Escolher foto do perfil": "Choose profile photo",
    "Escolher pasta…": "Choose folder…",
    "Esconder de novo as tarefas ocultas": "Hide hidden tasks again",
    "Escreva no campo acima e pressione Enter. O instante do áudio fica guardado junto.": "Type in the field above and press Return. The audio timestamp is saved with it.",
    "Escreva o nome primeiro": "Enter a name first",
    "Espaço local": "Local space",
    "este participante": "this participant",
    "Exclui em %d dias": "Deletes in %d days",
    "Exclui em 1 dia": "Deletes in 1 day",
    "Exclui em 30 dias": "Deletes in 30 days",
    "Exclui hoje": "Deletes today",
    "Excluindo...": "Deleting…",
    "Excluir equipe e dados": "Delete team and data",
    "Excluir esta equipe para todos?": "Delete this team for everyone?",
    "Excluir perfil deste Mac?": "Delete this profile from this Mac?",
    "Excluir perfil e dados pessoais": "Delete profile and personal data",
    "Exemplo": "Example",
    "Exibir ficha automaticamente após processar": "Show details automatically after processing",
    "expirada": "expired",
    "Externos": "External",
    "Falante %@": "Speaker %@",
    "Fale — o texto aparece aqui.": "Start speaking — text appears here.",
    "Falha ao remover do iCloud": "Could not remove from iCloud",
    "Falha de sincronização do iCloud": "iCloud sync failed",
    "Falha na fila do iCloud": "iCloud queue failed",
    "Favoritar": "Add to Favorites",
    "Fechar (Esc)": "Close (Esc)",
    "Gravação cancelada — nenhum arquivo foi criado.": "Recording canceled — no file was created.",
    "Gravação de %@": "Recording from %@",
    "Gravações": "Recordings",
    "Gravações e anexos ficarão prontos para transcrever. Você inicia o processamento pela aba Transcrição.": "Recordings and attachments will be ready to transcribe. Start processing from the Transcript tab.",
    "Gravado em": "Recorded on",
    "Gravado em %@ · Importado em %@": "Recorded on %@ · Imported on %@",
    "Grave áudio, importe um arquivo ou arraste aqui do Finder.": "Record audio, import a file, or drag one here from Finder.",
    "Grave, transcreva e revise suas conversas.": "Record, transcribe, and review your conversations.",
    "Grave, transcreva e revise suas conversas. O áudio fica no seu Mac, e a transcrição começa assim que você finalizar.": "Record, transcribe, and review your conversations. Audio stays on your Mac, and transcription begins as soon as you finish.",
    "Ignorar": "Ignore",
    "Imagem": "Image",
    "Imagem colada": "Pasted image",
    "Importa as reuniões marcadas para a biblioteca.": "Imports selected meetings into the library.",
    "Importado em": "Imported on",
    "Importado para o app em %@": "Imported into the app on %@",
    "Importar selecionadas": "Import selected",
    "Importe reuniões do Granola para a biblioteca, com transcrição quando o plano permitir.": "Import Granola meetings into the library, with transcripts when your plan allows.",
    "Importe reuniões futuras do Google Calendar para a biblioteca.": "Import upcoming Google Calendar meetings into the library.",
    "Inicia a reprodução a partir de %@.": "Starts playback at %@.",
    "Inicie a transcrição quando quiser. O resumo será gerado em seguida, respeitando a fila de processamento.": "Start transcription whenever you are ready. The summary will follow, respecting the processing queue.",
    "Interlocutor · áudio do sistema": "Other speaker · system audio",
    "Já usava esta equipe antes do acesso por código?": "Were you already using this team before code access?",
    "Login com Apple": "Sign in with Apple",
    "menos de 1 min": "under 1 min",
    "Mova o arquivo para a lixeira antes de apagá-lo definitivamente.": "Move the file to Trash before deleting it permanently.",
    "Movendo para a lixeira…": "Moving to Trash…",
    "Mover para Lixeira": "Move to Trash",
    "Mudar": "Change",
    "Mudar Equipe": "Switch team",
    "Na pasta %@": "In %@",
    "Nada com esse filtro": "No results for this filter",
    "Não consegui acessar esse áudio. Se ele estiver no iPhone, desbloqueie o aparelho e tente importar de novo.": "Could not access this audio. If it is on your iPhone, unlock it and try importing again.",
    "não foi possível abrir a pasta de suporte do app": "could not open the app support folder",
    "Não foi possível abrir o áudio desta conversa": "Could not open this conversation's audio",
    "Não foi possível adicionar a mídia": "Could not add media",
    "Não foi possível apagar o arquivo definitivamente: %@": "Could not permanently delete the file: %@",
    "Não foi possível baixar as conversas da equipe: %@": "Could not download team conversations: %@",
    "Não foi possível copiar o áudio da reunião: %@": "Could not copy meeting audio: %@",
    "Não foi possível criar arquivo da reunião: %@": "Could not create the meeting file: %@",
    "Não foi possível duplicar: %@. A cópia incompleta permaneceu no armazenamento para não apagar dados de forma insegura.": "Could not duplicate: %@. The incomplete copy was kept in storage to avoid deleting data unsafely.",
    "Não foi possível excluir a conta": "Could not delete account",
    "Não foi possível guardar a foto do perfil: %@": "Could not save profile photo: %@",
    "Não foi possível guardar a sincronização pendente de %@: %@": "Could not save pending sync for %@: %@",
    "Não foi possível guardar sua sessão: %@": "Could not save your session: %@",
    "Não foi possível validar a credencial da Apple.": "Could not validate Apple credential.",
    "Nenhum informado": "None specified",
    "Nenhum membro": "No members",
    "Nenhum microfone disponível.": "No microphone available.",
    "Nenhum resultado": "No results",
    "Nenhuma fala reconhecida neste áudio.": "No speech was recognized in this audio.",
    "Nenhuma mídia ainda": "No media yet",
    "Nenhuma mídia encontrada": "No media found",
    "Nenhuma nota ainda": "No notes yet",
    "Nenhuma reunião acessível nesta conta.": "No meetings are accessible with this account.",
    "Nenhuma reunião futura encontrada.": "No upcoming meetings found.",
    "NOTA": "NOTE",
    "notas": "notes",
    "O arquivo de áudio escolhido não foi encontrado.": "The selected audio file was not found.",
    "O arquivo sai do seu Mac e não poderá ser recuperado.": "The file will be removed from your Mac and cannot be recovered.",
    "O código e o link atuais deixarão de funcionar. Por segurança, os participantes aceitos precisarão entrar novamente com o novo código.": "The current code and link will stop working. For security, approved participants must join again with the new code.",
    "O download continua de onde parou se a conexão cair.": "The download resumes where it left off if your connection drops.",
    "O que aconteceu aqui? Use #etiqueta para agrupar": "What happened here? Use #tags to group notes",
    "O que cabe nesta aba": "What belongs in this tab",
    "obrigatório": "required",
    "Ouvindo…": "Listening…",
    "Ouvir a partir de %@": "Listen from %@",
    "Ouvir a partir desta palavra": "Listen from this word",
    "Painel de Mídias": "Media Board",
    "Parar e transcrever": "Stop and transcribe",
    "Participante aceito": "Participant accepted",
    "Participantes não informados": "Participants not specified",
    "PASTA": "FOLDER",
    "Pasta ativa: %@": "Active folder: %@",
    "Pastas da biblioteca": "Library folders",
    "Pausar transcrições e resumos automáticos": "Pause automatic transcripts and summaries",
    "PDF colado": "Pasted PDF",
    "Peça o código ao administrador da equipe.": "Ask the team admin for the code.",
    "pendente": "pending",
    "Permissão de %@": "%@ permission",
    "Pesquisa": "Research",
    "Pesquisar na transcrição: Cmd + F": "Search transcript: Cmd + F",
    "Pessoal": "Personal",
    "Posição do áudio": "Audio position",
    "Prazo perto": "Due soon",
    "Preferências": "Preferences",
    "Preparando a biblioteca. Gravar e importar estarão disponíveis em instantes.": "Preparing the library. Recording and importing will be available shortly.",
    "Preparando áudio": "Preparing audio",
    "Preparando biblioteca": "Preparing library",
    "Primeira rodada de testes do fluxo de cadastro.": "First round of onboarding flow tests.",
    "Pronto para transcrever": "Ready to transcribe",
    "Remove deste Mac o perfil e seus dados pessoais, sem apagar os espaços de equipe nem as preferências do app.": "Removes this profile and its personal data from this Mac without deleting team spaces or app preferences.",
    "Remover %@?": "Remove %@?",
    "Remover acesso": "Remove access",
    "Remover da pasta": "Remove from folder",
    "Remover pessoa": "Remove person",
    "Removido": "Removed",
    "Reprocessar": "Reprocess",
    "Restaurar %@": "Restore %@",
    "Restaurar a pasta %@": "Restore %@ folder",
    "Restaurar arquivo": "Restore file",
    "Restaurar padrão": "Restore default",
    "Restaurar pasta": "Restore folder",
    "Restaurar tarefa": "Restore task",
    "Restaurar todos os arquivos da lixeira": "Restore all files from Trash",
    "Restaurar Tudo": "Restore All",
    "Restaure a pasta inteira, com a cor e a imagem que tinha, ou traga de volta só uma conversa.": "Restore the entire folder with its original color and image, or bring back just one conversation.",
    "Resumo indisponível": "Summary unavailable",
    "Reuniões acessíveis": "Accessible meetings",
    "Reuniões futuras (próximas 24 horas)": "Upcoming meetings (next 24 hours)",
    "Salta o áudio para o instante desta palavra.": "Jumps audio to this word's timestamp.",
    "Salvar aqui": "Save here",
    "Salvar configurações": "Save settings",
    "Sem cor": "No color",
    "SEM RESPONSÁVEL": "NO ASSIGNEE",
    "Sobre a página de mídias": "About the Media page",
    "Sobre nomear vozes": "About naming speakers",
    "Soltar para adicionar": "Drop to add",
    "Somado a partir dos nomes de Equipe e Externos.": "Combined from Team and External names.",
    "Somente a conta que criou a equipe pode consultar participantes, alterar configurações, trocar o código ou excluir a equipe.": "Only the account that created the team can view participants, change settings, change the code, or delete the team.",
    "TAREFA": "TASK",
    "Tarefa removida de %@. Restaure para voltar ao painel de tarefas dessa conversa.": "Task removed from %@. Restore it to return it to this conversation's task board.",
    "Temas": "Topics",
    "Tentar agora": "Try now",
    "TRANSCRIÇÃO": "TRANSCRIPT",
    "Transcrição finalizada sem falas": "Transcription finished with no speech",
    "Trocar código de entrada": "Change join code",
    "Trocar código e revogar acessos": "Change code and revoke access",
    "Trocar foto do perfil": "Change profile photo",
    "Trocar o código cria um novo compartilhamento e exige que os participantes entrem novamente. Excluir a equipe apaga a zona compartilhada e os dados locais deste Mac.": "Changing the code creates a new share and requires participants to join again. Deleting the team removes the shared zone and this Mac's local data.",
    "Trocar o código de entrada?": "Change the join code?",
    "Vem da duração do áudio desta conversa.": "Based on this conversation's audio duration.",
    "Ver a conversa": "View conversation",
    "Ver quem participou": "View participants",
    "Vídeo colado": "Pasted video",
    "Visibilidade dos arquivos": "File visibility",
    "Você ainda não faz parte de nenhuma equipe.": "You are not part of a team yet.",
    "Você ainda não tem equipes. Use o + para criar a primeira ou entre com um código.": "You do not have any teams yet. Use + to create your first or join one with a code.",
    "Você precisa desbloquear seu iPhone antes de importar esse áudio.": "Unlock your iPhone before importing this audio.",
    "Você será avisado quando a transcrição terminar.": "You will be notified when transcription finishes.",
    "Você também pode apontar uma pasta que já tenha os modelos GGUF.": "You can also choose a folder that already contains the GGUF models.",
    "Voltar 10 segundos": "Back 10 seconds",
    "Voltar para a gravação": "Back to recording",
    "Voltar para todas as pastas": "Back to all folders",
    ": %@": ": %@",
    "8 conversas": "8 conversations",
    "A biblioteca ainda está abrindo — a conexão com o Google Calendar aparece aqui em instantes.": "The library is still opening — Google Calendar connection will appear here shortly.",
    "A biblioteca ainda está abrindo — a conexão com o Granola aparece aqui em instantes.": "The library is still opening — Granola connection will appear here shortly.",
    "A biblioteca ainda não abriu.": "The library has not opened yet.",
    "A conversa saiu deste Mac, mas a remoção não entrou na fila do iCloud: %@": "Conversation was removed from this Mac, but deletion was not queued on iCloud: %@",
    "A entrada por código está ativa.": "Code access is active.",
    "A gravação não estava na pasta esperada da biblioteca.": "Recording was not found in the expected library folder.",
    "A imagem cobre a cor. O texto do cartão ganha um véu escuro por cima dela para continuar legível.": "The image covers the color. Card text has a dark overlay to maintain readability.",
    "A lista vem diretamente do compartilhamento do iCloud. O CloudKit não disponibiliza os e-mails das Apple Accounts.": "The list comes directly from iCloud Sharing. CloudKit does not provide Apple Account emails.",
    "A pasta estava vazia. Restaure para tê-la de volta com a cor e a imagem que tinha.": "The folder was empty. Restore it to bring back its original color and image.",
    "A pasta é só um rótulo. Nada mais será removido.": "The folder is just a label. Nothing else will be removed.",
    "A senha é gerenciada pelo seu ID Apple. Para alterar, use os ajustes da sua conta Apple.": "Password is managed by your Apple ID. To change it, use your Apple Account settings.",
    "A transcrição aparecerá depois do processamento.": "Transcription will appear after processing.",
    "A transcrição, as notas e o resumo continuam aqui. Restaure o áudio pela Lixeira do app — assim ele volta com o nome que a reprodução espera.": "Transcript, notes, and summary remain here. Restore audio from Trash to keep playback intact.",
    "A zona do CloudKit, as conversas compartilhadas e os dados deste Mac serão apagados. Outros Macs atualizados removem suas cópias ao se conectarem ao iCloud. Esta ação não pode ser desfeita.": "The CloudKit zone, shared conversations, and local data on this Mac will be deleted. This action cannot be undone.",
    "AO VIVO": "LIVE",
    "ARQUIVO": "FILE",
    "Abre o navegador do macOS para autorizar o Ōmu na sua conta do Granola.": "Opens your browser to authorize Ōmu with your Granola account.",
    "Abre o navegador para autorizar o Ōmu na sua conta Google.": "Opens your browser to authorize Ōmu with your Google account.",
    "Adicionar pessoa": "Add person",
    "Alterar Senha": "Change Password",
    "Alterar permissão": "Change permission",
    "Anexo removido da mídia de %@. Restaure para voltar à aba Mídia dessa conversa.": "Attachment removed from %@ media. Restore to return it to the Media tab.",
    "Apaga as credenciais do Google Calendar do Keychain.": "Deletes Google Calendar credentials from Keychain.",
    "Apaga as credenciais do Granola do Keychain.": "Deletes Granola credentials from Keychain.",
    "Apagado em %@": "Deleted on %@",
    "Apagar %@ definitivamente?": "Delete %@ permanently?",
    "Apagar a pasta %@?": "Delete folder %@?",
    "Apagar de vez": "Delete permanently",
    "Apagar definitivamente %@": "Delete %@ permanently",
    "Apagar definitivamente a pasta %@": "Delete folder %@ permanently",
    "Apagar definitivamente todos os arquivos da lixeira": "Delete all files in trash permanently",
    "Apagar tarefa definitivamente": "Delete task permanently",
    "Aparência %@": "Appearance %@",
    "Aparência do app, os cartões da biblioteca e quando as transcrições começam.": "App appearance, library cards, and when transcriptions begin.",
    "Apple Account compartilhada": "Shared Apple Account",
    "Arquivo colado": "Pasted file",
    "Arquivo importado: um canal só, sem separação de falante.": "Imported file: single channel, without speaker separation.",
    "As %d conversas continuam na biblioteca — só deixam de estar nesta pasta.": "%d conversations remain in your library — they simply leave this folder.",
    "As notas também foram descartadas porque a gravação era curta demais para criar um arquivo.": "Notes were also discarded because the recording was too short to create a file.",
    "Atalhos da biblioteca": "Library shortcuts",
    "Atenção": "Warning",
    "Ações de %@": "Actions for %@",
    "Baixar": "Download",
    "Baixar modelos (%@)": "Download models (%@)",
    "Biblioteca de Conversas": "Conversation Library",
    "Biblioteca de Conversas (Pastas)": "Conversation Library (Folders)",
    "Cada nota fica presa a um instante. Clique no tempo para ouvir o trecho, e use #etiquetas para agrupar depois.": "Each note is pinned to a timestamp. Click the time to listen, and use #tags to group later.",
    "Canal misto ou desconhecido": "Mixed or unknown channel",
    "Cancelar o processamento e mover para a lixeira": "Cancel processing and move to trash",
    "Cancelar processamento": "Cancel processing",
    "Carregando participantes…": "Loading participants…",
    "Carregando reuniões…": "Loading meetings…",
    "Cartões da biblioteca": "Library cards",
    "Client ID/Secret não configurados": "Client ID/Secret not configured",
    "Clique ou arraste do Finder": "Click or drag from Finder",
    "Clique para ver a conversa": "Click to view conversation",
    "Clique para voltar à tela de gravação.": "Click to return to recording screen.",
    "Como funcionam as notas": "How notes work",
    "Como funcionam os modelos": "How models work",
    "Como funciona o Google Calendar": "How Google Calendar works",
    "Como funciona o Granola": "How Granola works",
    "Como funciona o microfone": "How microphone works",
    "Como funciona o processamento": "How processing works",
    "Compartilhamentos no iCloud": "iCloud Shares",
    "Conectado ao Google Calendar": "Connected to Google Calendar",
    "Conectado ao Granola": "Connected to Granola",
    "Conectado, o Ōmu pode ver suas reuniões futuras do Google Calendar e importá-las para a biblioteca — apenas título, data e participantes. Nada é enviado para fora do seu Mac além do fluxo de autorização e das chamadas ao próprio Google.": "Connected, Ōmu can view upcoming Google Calendar meetings and import title, date, and attendees locally. Nothing leaves your Mac.",
    "Conectar": "Connect",
    "Conexões": "Connections",
    "Confirmar": "Confirm",
    "Confirmar exclusão": "Confirm deletion",
    "Conta": "Account",
    "Conversas recentes": "Recent conversations",
    "Copiar": "Copy",
    "Copiar código": "Copy code",
    "Copiar link": "Copy link",
    "Copiar texto": "Copy text",
    "Cor padrão": "Default color",
    "Data de criação": "Creation date",
    "Data de modificação": "Modification date",
    "Data e hora da reunião": "Meeting date & time",
    "Deixar equipe": "Leave team",
    "Deixar esta equipe?": "Leave this team?",
    "Desconectar": "Disconnect",
    "Desconectar conta Google": "Disconnect Google account",
    "Desconectar conta Granola": "Disconnect Granola account",
    "Descrição da reunião": "Meeting description",
    "Diarização de falantes": "Speaker Diarization",
    "Diarização local": "Local Diarization",
    "Duração da conversa": "Conversation duration",
    "Duração da gravação": "Recording duration",
    "Duração total": "Total duration",
    "Dê um nome de verdade a cada voz identificada pela diarização. Isso atualiza todas as falas dela na transcrição de uma vez.": "Give each diarized voice a real name. This updates all of their dialogue in the transcript at once.",
    "E-mail do entrevistado": "Interviewee email",
    "E-mail dos entrevistadores": "Interviewers email",
    "Entrada por código": "Code access",
    "Entrar na equipe": "Join team",
    "Entrar por código": "Join via code",
    "Entrevistado não informado": "Interviewee not specified",
    "Entrevistador não informado": "Interviewer not specified",
    "Erro ao conectar": "Connection error",
    "Erro ao excluir": "Deletion error",
    "Erro ao exportar": "Export error",
    "Erro ao importar": "Import error",
    "Erro de transcrição": "Transcription error",
    "Erro do Keychain (%d).": "Keychain error (%d).",
    "Escolha a conversa, descreva a tarefa e defina prioridade, responsável e data limite.": "Choose conversation, describe task, and set priority, assignee, and due date.",
    "Escolha em qual equipe você quer trabalhar agora.": "Choose which team you want to work in now.",
    "Escolha o arquivo de áudio da reunião": "Choose meeting audio file",
    "Escolha o que aparece nos cartões da biblioteca. Vale para todos.": "Choose what appears on library cards. Applies to all.",
    "Escolha onde salvar %@": "Choose where to save %@",
    "Escolha onde salvar a pasta %@": "Choose where to save folder %@",
    "Escolha uma imagem para a faixa": "Choose an image for banner",
    "Escolher arquivo": "Choose file",
    "Escolher conversa": "Choose conversation",
    "Escolher participante": "Choose participant",
    "Escola / Trabalho": "School / Work",
    "Essa Apple Account não poderá mais ler nem alterar as conversas da equipe.": "This Apple Account will no longer be able to read or modify team conversations.",
    "Esta ação não pode ser desfeita. Seu perfil, conversas pessoais, áudios, transcrições, notas, tarefas, vínculos de equipe e conexões com Google Calendar e Granola serão removidos deste Mac. Os dados dos espaços de equipe, as preferências do app e os compartilhamentos do iCloud serão preservados.": "This action cannot be undone. Your profile, personal conversations, audio, transcripts, notes, tasks, and integrations will be removed from this Mac.",
    "Esta pasta não contém conversas para exportar.": "This folder has no conversations to export.",
    "Estas preferências são compartilhadas no iCloud. A política de revisão de recebimento será aplicada ao fluxo de arquivos em uma próxima etapa; ainda não bloqueia automaticamente envios.": "These preferences sync via iCloud.",
    "Este nome será exibido para todas as pessoas desta equipe.": "This name will be displayed to everyone on this team.",
    "Ex.: Ana Silva": "e.g., Ana Silva",
    "Ex.: Entrevista com Stakeholders - UX Research": "e.g., Stakeholder Interview - UX Research",
    "Ex.: João Santos": "e.g., João Santos",
    "Ex.: Revisar documentação": "e.g., Review documentation",
    "Ex.: Revisar pontos da entrevista": "e.g., Review interview points",
    "Excluir da equipe": "Remove from team",
    "Excluir equipe": "Delete team",
    "Excluir esta conversa?": "Delete this conversation?",
    "Excluir esta pasta?": "Delete this folder?",
    "Excluir reunião": "Delete meeting",
    "Exibir ficha automaticamente": "Show details sheet automatically",
    "Exportado com sucesso": "Exported successfully",
    "Exportando…": "Exporting…",
    "Falha ao carregar": "Failed to load",
    "Falha ao salvar": "Failed to save",
    "Falha no processamento": "Processing failed",
    "Ficha": "Details",
    "Ficha da entrevista": "Interview details",
    "Formato de áudio": "Audio format",
    "Foto": "Photo",
    "Foto de %@": "Photo of %@",
    "Foto, vídeo, áudio ou arquivo": "Photo, video, audio, or file",
    "Foto, vídeo, áudio ou arquivo. Também aceita arrastar do Finder.": "Photo, video, audio, or file. Dragging from Finder is also supported.",
    "Fotos, vídeos, áudios e outros anexos de todas as conversas, reunidos num só lugar.": "Photos, videos, audio, and attachments from all conversations in one place.",
    "Fotos, vídeos, áudios e outros anexos salvos em qualquer conversa aparecerão reunidos aqui.": "Photos, videos, audio, and attachments saved in any conversation will appear here.",
    "Fotos, vídeos, áudios, documentos e anexos salvos nesta conversa.": "Photos, videos, audio, documents, and attachments saved in this conversation.",
    "Gera um novo resumo a partir da transcrição atual, sem re-transcrever": "Generates a new summary from current transcript without re-transcribing",
    "Gerando novo resumo…": "Generating new summary…",
    "Gerar nova conversa": "Generate new conversation",
    "Gerar novo resumo": "Generate new summary",
    "Gerenciada pelo ID Apple": "Managed by Apple ID",
    "Gerencie as tarefas geradas a partir das suas conversas.": "Manage tasks generated from your conversations.",
    "Gerencie conversas excluídas. Itens na lixeira serão removidos permanentemente após 30 dias.": "Manage deleted conversations. Items in trash will be permanently removed after 30 days.",
    "Gerencie suas pastas de conversas.": "Manage your conversation folders.",
    "Gerencie suas transcrições e insights de conversas.": "Manage your transcripts and conversation insights.",
    "Google Calendar": "Google Calendar",
    "Gravação descartada": "Recording discarded",
    "Gravação em andamento": "Recording in progress",
    "Gravação finalizada": "Recording completed",
    "Gravar áudio do sistema": "Record system audio",
    "Gravar microfone": "Record microphone",
    "Gravado em %@": "Recorded on %@",
    "Identidade": "Identity",
    "Identidade visual": "Visual identity",
    "Identificadas automaticamente na transcrição. Aceite para mandar para o quadro de tarefas, edite antes de aceitar ou descarte.": "Automatically identified in transcript. Accept to send to board, edit before accepting, or discard.",
    "Importação concluída": "Import completed",
    "Importação falhou": "Import failed",
    "Importado": "Imported",
    "Importado em %@": "Imported on %@",
    "Importados": "Imported",
    "Informações Pessoais": "Personal Information",
    "Informações da Conta": "Account Information",
    "Informações da pasta": "Folder details",
    "Inglês (US)": "English (US)",
    "Insira o código da equipe": "Enter team code",
    "Iniciar sessão com Apple": "Sign in with Apple",
    "Iniciais": "Initials",
    "Integrar": "Integrate",
    "Integrações": "Integrations",
    "Inteligência e Modelos": "Intelligence & Models",
    "Itens na lixeira": "Items in trash",
    "Janela flutuante": "Floating window",
    "Limite de tempo": "Time limit",
    "Limpar tudo": "Clear all",
    "Localização": "Localization",
    "Mais recentes primeiro": "Newest first",
    "Mais antigas primeiro": "Oldest first",
    "Mantém o app claro, mesmo com o Mac no escuro.": "Keeps the app light, even when your Mac is in dark mode.",
    "Mantém o app escuro, mesmo com o Mac no claro.": "Keeps the app dark, even when your Mac is in light mode.",
    "Marcador": "Bookmark",
    "Medidor de áudio": "Audio meter",
    "Membro desde %@": "Member since %@",
    "Membros da equipe": "Team members",
    "Mensagem": "Message",
    "Meu Perfil": "My Profile",
    "Microfone e Áudio": "Microphone & Audio",
    "Minhas reuniões": "My meetings",
    "Modalidade": "Format",
    "Modalidade não informada": "Format not specified",
    "Modelo %@": "Model %@",
    "Modelo de transcrição": "Transcription model",
    "Modelo do cartão": "Card template",
    "Modelos de diarização não estagiados. Rode Scripts/bootstrap-runtimes.sh.": "Diarization models missing. Run Scripts/bootstrap-runtimes.sh.",
    "Modelos locais": "Local models",
    "Mostrar %@": "Show %@",
    "Mostrar %@ no Finder": "Show %@ in Finder",
    "Mostrar confiança": "Show confidence",
    "Mostrar no Finder": "Show in Finder",
    "Mostrar painel flutuante durante a gravação": "Show floating panel during recording",
    "Mostrar porcentagem de confiança": "Show confidence percentage",
    "Mover para…": "Move to…",
    "Mover todos para a lixeira": "Move all to trash",
    "Mudar cor": "Change color",
    "Mudar papel": "Change role",
    "Nada aqui": "Nothing here",
    "Não foi possível abrir a biblioteca: %@": "Could not open library: %@",
    "Não foi possível aceitar o convite do iCloud: %@": "Could not accept iCloud invite: %@",
    "Não foi possível apagar definitivamente “%@”: %@": "Could not permanently delete “%@”: %@",
    "Não foi possível apagar o anexo: %@": "Could not delete attachment: %@",
    "Não foi possível apagar o perfil: %@": "Could not delete profile: %@",
    "Não foi possível criar a equipe no iCloud: %@": "Could not create team on iCloud: %@",
    "Não foi possível criar a pasta: %@": "Could not create folder: %@",
    "Não foi possível duplicar: %@": "Could not duplicate: %@",
    "Não foi possível entrar": "Could not sign in",
    "Não foi possível entrar na equipe: %@": "Could not join team: %@",
    "Não foi possível exportar: %@": "Could not export: %@",
    "Não foi possível importar a reunião: %@": "Could not import meeting: %@",
    "Não foi possível ler ou salvar a fila do iCloud: %@": "Could not read or save iCloud queue: %@",
    "Não foi possível mover o arquivo para a lixeira: %@": "Could not move file to trash: %@",
    "Não foi possível recuperar o arquivo: %@": "Could not recover file: %@",
    "Não foi possível remover esse arquivo: %@": "Could not remove this file: %@",
    "Não foi possível renomear: %@": "Could not rename: %@",
    "Não foi possível salvar a diarização: %@": "Could not save diarization: %@",
    "Não foi possível salvar a transcrição: %@": "Could not save transcription: %@",
    "Não foi possível salvar as informações: %@": "Could not save details: %@",
    "Não foi possível salvar as notas: %@": "Could not save notes: %@",
    "Não foi possível salvar: %@": "Could not save: %@",
    "Não informado": "Not specified",
    "Não iniciado": "To Do",
    "Nenhum anexo": "No attachments",
    "Nenhum membro encontrado": "No members found",
    "Nenhum participante": "No participants",
    "Nenhum participante encontrado": "No participants found",
    "Nenhuma reunião pendente": "No pending meetings",
    "Ninguém informado na ficha.": "No one specified on sheet.",
    "Nome Completo": "Full Name",
    "Nome na equipe": "Name in team",
    "Nome, e-mail ou login": "Name, email, or username",
    "Notas da Reunião": "Meeting Notes",
    "Notas durante a gravação": "Notes during recording",
    "Nova Nota": "New Note",
    "Nova Tarefa": "New Task",
    "O reconhecimento de fala não está disponível agora.": "Speech recognition is not available right now.",
    "O resumo aparecerá depois do processamento.": "Summary will appear after processing.",
    "Ocorrência anterior (Shift+Enter)": "Previous occurrence (Shift+Enter)",
    "Opções da conversa": "Conversation options",
    "Opções de compartilhamento": "Sharing options",
    "Ou digite nome, e-mail ou login": "Or type name, email, or username",
    "Ouvir áudio": "Listen to audio",
    "Papel": "Role",
    "Pasta destino": "Destination folder",
    "Pastas da Biblioteca": "Library Folders",
    "Permissão": "Permission",
    "Permissões": "Permissions",
    "Personalizar": "Customize",
    "Personalizar cartões": "Customize cards",
    "Por data": "By date",
    "Por nome": "By name",
    "Por prioridade": "By priority",
    "Por status": "By status",
    "Português (Brasil)": "Portuguese (Brazil)",
    "Próxima ocorrência (Enter)": "Next occurrence (Enter)",
    "Próximas 24h": "Next 24 hours",
    "Quando ativado, novos áudios não entram na fila até você selecionar Transcrever.": "When enabled, new audio stays queued until you select Transcribe.",
    "Quando desligado, a ficha não abre automaticamente ao fim do processamento — ideal quando a ficha já foi preenchida pelo calendário.": "When disabled, details sheet will not pop up after processing.",
    "Quando desligado, as palavras continuam destacadas por cor, mas o percentual não aparece.": "When disabled, word confidence colors remain but numbers are hidden.",
    "Quando uma conversa tiver próximos passos ou tarefas criadas, elas ficarão reunidas nesta página.": "When conversations have next steps or tasks, they will appear here.",
    "Quem é quem?": "Who is who?",
    "Reativar som": "Unmute",
    "Recebimento de arquivos": "File Reception",
    "Recentes": "Recent",
    "Reconfigurar acesso por código": "Reconfigure code access",
    "Refinando com o modelo local…": "Refining with local model…",
    "Registrado": "Registered",
    "Regras de Prazo": "Due Date Rules",
    "Remover": "Remove",
    "Remover da lista": "Remove from list",
    "Repetir": "Repeat",
    "Reproduzindo": "Playing",
    "Resumo da Reunião": "Meeting Summary",
    "Retomar": "Resume",
    "Retomar transcrição": "Resume transcription",
    "Reunião sem título": "Untitled meeting",
    "Reuniões do Calendário": "Calendar Meetings",
    "Reuniões pendentes": "Pending meetings",
    "Salvo no Mac": "Saved to Mac",
    "Salvar como…": "Save as…",
    "Segurança do Perfil": "Profile Security",
    "Selecione uma pasta": "Select a folder",
    "Sem descrição": "No description",
    "Sem título": "Untitled",
    "Senha": "Password",
    "Seu nome": "Your name",
    "Sincronizado com o iCloud": "Synced with iCloud",
    "Sincronizando com o iCloud…": "Syncing with iCloud…",
    "Sobre Configurações": "About Settings",
    "Sobre a biblioteca": "About library",
    "Sobre o aplicativo": "About application",
    "Substituir arquivo": "Replace file",
    "Tamanho do arquivo": "File size",
    "Tarefas da Conversa": "Conversation Tasks",
    "Tarefas pendentes": "Pending tasks",
    "Tempo de gravação": "Recording time",
    "Tentar novamente": "Try again",
    "Tente limpar a seleção ou buscar por outra conversa.": "Try clearing selection or searching for another conversation.",
    "Tente limpar a seleção, trocar o tipo de arquivo ou buscar por outra conversa.": "Try clearing selection, switching file type, or searching for another conversation.",
    "Tipo": "Type",
    "Tipo de arquivo": "File type",
    "Todas as mídias": "All media",
    "Todos os arquivos": "All files",
    "Todos os membros": "All members",
    "Todos os status": "All statuses",
    "Todos os tipos": "All types",
    "Transcrevendo…": "Transcribing…",
    # Fases curtas mostradas diretamente nos cartões da biblioteca.
    "distinguindo falantes…": "distinguishing speakers…",
    "Escolher…": "Choose…",
    "resolvendo falantes pelo contexto…": "resolving speakers from context…",
    "resumindo…": "summarizing…",
    "salvando…": "saving…",
    "transcrevendo…": "transcribing…",
    "traduzindo…": "translating…",
    "Traduzir automaticamente para o idioma do sistema": "Automatically translate to the system language",
    "Quando ligado, transcrições e resumos em outro idioma são traduzidos localmente para português ou inglês. Quando desligado, o idioma falado é preservado.": "When enabled, transcripts and summaries in another language are translated locally into Portuguese or English. When disabled, the spoken language is preserved.",
    "Trocar…": "Change…",
    "Transcrição concluída": "Transcription complete",
    "Transcrição em preparação": "Preparing transcription",
    "Transcrição falhou": "Transcription failed",
    "Troque o filtro para ver as outras notas.": "Change filter to view other notes.",
    "Uma janela pequena, sempre visível por cima dos outros apps, para anotar, pausar e finalizar sem voltar ao Ōmu.": "A compact floating window to take notes, pause, and finish without switching back to Ōmu.",
    "Usar imagem": "Use image",
    "Usar pasta do app": "Use app folder",
    "Use esta ação uma vez para que o código também libere a zona compartilhada no iCloud. Convites pendentes por e-mail deixam de valer.": "Use this once to release the shared iCloud zone.",
    "Use o botão de adicionar para criar uma tarefa nesta conversa.": "Use the add button to create a task in this conversation.",
    "Vincular": "Link",
    "Vincular conta": "Link account",
    "Visualizar": "Preview",
    "Voltar para a lista": "Back to list"
}

def main():
    merged = dict(TRANSLATIONS)
    merged.update(EXTRA_TRANSLATIONS)

    # Verifica se ainda resta alguma chave do tmp/keys.json
    if os.path.exists("tmp/keys.json"):
        with open("tmp/keys.json", "r", encoding="utf-8") as f:
            all_keys = json.load(f)
        missing = [k for k in all_keys if k not in merged]
        for m in missing:
            # Fallback inteligente para chaves dinâmicas ou raras
            merged[m] = m

    generate_xcstrings(merged, "Papagaio/Localizable.xcstrings")
    print(f"Successfully generated catalog with {len(merged)} total strings!")

if __name__ == "__main__":
    main()
